from pyspark import Row

from tests.utils.spark_util import spark_tests as spark

DF_CLUSTERING_OUTPUT_ASSIGNMENT = spark.createDataFrame(
    [
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11215",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11225",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11255",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11286",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11294",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11314",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11323",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11351",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11364",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11367",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11384",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11388",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11414",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11418",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11436",
            store_cluster=1,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11453",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11463",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11465",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11486",
            store_cluster=1,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="11489",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="12083",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="12543",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="12544",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="12664",
            store_cluster=1,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="13025",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="13047",
            store_cluster=1,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="13051",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="13546",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="14544",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="15264",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="15285",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="15445",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="16305",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="18205",
            store_cluster=2,
        ),
        Row(
            REGION="ontario",
            BANNER="SOBEYS",
            STORE_PHYSICAL_LOCATION_NO="22630",
            store_cluster=2,
        ),
    ]
)
