from pyspark import Row

from tests.utils.spark_util import spark_tests as spark


DF_COMBINED_SALES_LEVELS = spark.createDataFrame(
    [
        Row(
            STORE_PHYSICAL_LOCATION_NO="11453",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=1.0,
            prop_qty_totals=10.0,
            NS_prop=0.1,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11453",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=1.0,
            prop_qty_totals=10.0,
            NS_prop=0.1,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11453",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=8.0,
            prop_qty_totals=10.0,
            NS_prop=0.8,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11453",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=2.0,
            prop_qty_totals=5.0,
            NS_prop=0.4,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11453",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="2",
            prop_qty=3.0,
            prop_qty_totals=5.0,
            NS_prop=0.6,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11286",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=1.0,
            prop_qty_totals=2.0,
            NS_prop=0.5,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11286",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=1.0,
            prop_qty_totals=2.0,
            NS_prop=0.5,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="13546",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=1.0,
            prop_qty_totals=6.0,
            NS_prop=0.16666666666666666,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="13546",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=1.0,
            prop_qty_totals=6.0,
            NS_prop=0.16666666666666666,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="13546",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=4.0,
            prop_qty_totals=6.0,
            NS_prop=0.6666666666666666,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="13546",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="2",
            prop_qty=3.0,
            prop_qty_totals=4.0,
            NS_prop=0.75,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="13546",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="3",
            prop_qty=1.0,
            prop_qty_totals=4.0,
            NS_prop=0.25,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="18205",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=2.0,
            prop_qty_totals=5.0,
            NS_prop=0.4,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="18205",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=3.0,
            prop_qty_totals=5.0,
            NS_prop=0.6,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="18205",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=2.0,
            prop_qty_totals=6.0,
            NS_prop=0.3333333333333333,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="18205",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=1.0,
            prop_qty_totals=6.0,
            NS_prop=0.16666666666666666,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="18205",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="2",
            prop_qty=3.0,
            prop_qty_totals=6.0,
            NS_prop=0.5,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="12083",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=1.0,
            prop_qty_totals=3.0,
            NS_prop=0.3333333333333333,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="12083",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="2",
            prop_qty=2.0,
            prop_qty_totals=3.0,
            NS_prop=0.6666666666666666,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="12083",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=2.0,
            prop_qty_totals=3.0,
            NS_prop=0.6666666666666666,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="12083",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=1.0,
            prop_qty_totals=3.0,
            NS_prop=0.3333333333333333,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11323",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=2.0,
            prop_qty_totals=17.0,
            NS_prop=0.11764705882352941,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11323",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=15.0,
            prop_qty_totals=17.0,
            NS_prop=0.8823529411764706,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11323",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="2",
            prop_qty=4.0,
            prop_qty_totals=7.0,
            NS_prop=0.5714285714285714,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11323",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="3",
            prop_qty=2.0,
            prop_qty_totals=7.0,
            NS_prop=0.2857142857142857,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11323",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=1.0,
            prop_qty_totals=7.0,
            NS_prop=0.14285714285714285,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11384",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=2.0,
            prop_qty_totals=9.0,
            NS_prop=0.2222222222222222,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11384",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=7.0,
            prop_qty_totals=9.0,
            NS_prop=0.7777777777777778,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11384",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=1.0,
            prop_qty_totals=5.0,
            NS_prop=0.2,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11384",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=4.0,
            prop_qty_totals=5.0,
            NS_prop=0.8,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11367",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=4.0,
            prop_qty_totals=5.0,
            NS_prop=0.8,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11367",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=1.0,
            prop_qty_totals=5.0,
            NS_prop=0.2,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11367",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="2",
            prop_qty=2.0,
            prop_qty_totals=3.0,
            NS_prop=0.6666666666666666,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11367",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=1.0,
            prop_qty_totals=3.0,
            NS_prop=0.3333333333333333,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11225",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=1.0,
            prop_qty_totals=1.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11225",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=1.0,
            prop_qty_totals=2.0,
            NS_prop=0.5,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11225",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="2",
            prop_qty=1.0,
            prop_qty_totals=2.0,
            NS_prop=0.5,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="14544",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=4.0,
            prop_qty_totals=4.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="14544",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=2.0,
            prop_qty_totals=4.0,
            NS_prop=0.5,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="14544",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="2",
            prop_qty=2.0,
            prop_qty_totals=4.0,
            NS_prop=0.5,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11388",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=3.0,
            prop_qty_totals=13.0,
            NS_prop=0.23076923076923078,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11388",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=10.0,
            prop_qty_totals=13.0,
            NS_prop=0.7692307692307693,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="15264",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=1.0,
            prop_qty_totals=3.0,
            NS_prop=0.3333333333333333,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="15264",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=2.0,
            prop_qty_totals=3.0,
            NS_prop=0.6666666666666666,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11255",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=1.0,
            prop_qty_totals=5.0,
            NS_prop=0.2,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11255",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=4.0,
            prop_qty_totals=5.0,
            NS_prop=0.8,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11463",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=2.0,
            prop_qty_totals=8.0,
            NS_prop=0.25,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11463",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=6.0,
            prop_qty_totals=8.0,
            NS_prop=0.75,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11465",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=1.0,
            prop_qty_totals=6.0,
            NS_prop=0.16666666666666666,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11465",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=5.0,
            prop_qty_totals=6.0,
            NS_prop=0.8333333333333334,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="15285",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=1.0,
            prop_qty_totals=4.0,
            NS_prop=0.25,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="15285",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=3.0,
            prop_qty_totals=4.0,
            NS_prop=0.75,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="12664",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=1.0,
            prop_qty_totals=1.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="12664",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=3.0,
            prop_qty_totals=5.0,
            NS_prop=0.6,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="12664",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=2.0,
            prop_qty_totals=5.0,
            NS_prop=0.4,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="22630",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="2",
            prop_qty=4.0,
            prop_qty_totals=4.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="22630",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=8.0,
            prop_qty_totals=9.0,
            NS_prop=0.8888888888888888,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="22630",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=1.0,
            prop_qty_totals=9.0,
            NS_prop=0.1111111111111111,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11436",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=4.0,
            prop_qty_totals=4.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11436",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=1.0,
            prop_qty_totals=1.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="13047",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=4.0,
            prop_qty_totals=4.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="13047",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=1.0,
            prop_qty_totals=1.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11364",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=4.0,
            prop_qty_totals=4.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11364",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="1",
            prop_qty=2.0,
            prop_qty_totals=2.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11486",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="-1",
            prop_qty=2.0,
            prop_qty_totals=2.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11486",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=5.0,
            prop_qty_totals=5.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="16305",
            POG_SECTION="Frozen Pizza",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="2",
            prop_qty=1.0,
            prop_qty_totals=1.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="16305",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=3.0,
            prop_qty_totals=3.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11215",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=9.0,
            prop_qty_totals=9.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11294",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=4.0,
            prop_qty_totals=4.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11314",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=12.0,
            prop_qty_totals=12.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11351",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=2.0,
            prop_qty_totals=2.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11414",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=1.0,
            prop_qty_totals=1.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11489",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=4.0,
            prop_qty_totals=4.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="12544",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=8.0,
            prop_qty_totals=8.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="13051",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=6.0,
            prop_qty_totals=6.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="15445",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=1.0,
            prop_qty_totals=1.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="11418",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=1.0,
            prop_qty_totals=1.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="12543",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=4.0,
            prop_qty_totals=4.0,
            NS_prop=1.0,
        ),
        Row(
            STORE_PHYSICAL_LOCATION_NO="13025",
            POG_SECTION="Frozen Handhelds",
            BANNER="SOBEYS",
            REGION="ontario",
            NEED_STATE="0",
            prop_qty=9.0,
            prop_qty_totals=9.0,
            NS_prop=1.0,
        ),
    ]
)
