from pyspark import Row

from tests.utils.spark_util import spark_tests as spark

DF_COMPETITOR_DASHBOARD_NAMES = spark.sparkContext.parallelize(
    [
        Row("Cmp_Ban_Type_49Th_Parallel_Grocery_0_10", "49th Parallel", "None"),
        Row(
            "Cmp_Ban_Type_49Th_Parallel_Grocery_Full_Service_10",
            "49th Parallel",
            "None",
        ),
        Row("Cmp_Ban_Type_Amazon_Inc_Full_Service_10", "Wholefoods ", "None"),
        Row("Cmp_Ban_Type_Avril_Ss_0_10", "Avril S", "None"),
        Row("Cmp_Ban_Type_Avril_Ss_Quebec_10", "Avril S - Quebec", "None"),
        Row("Cmp_Ban_Type_Clover_Farm_Full_Service_10", "Clover Farm ", "None"),
        Row("Cmp_Ban_Type_Coleman_Group_Full_Service_10", "Coleman ", "None"),
        Row("Cmp_Ban_Type_Coop_Atlantic_Full_Service_10", "Coop Atl ", "None"),
        Row("Cmp_Ban_Type_Coop_Federated_0_10", "Coop Federated", "None"),
        Row("Cmp_Ban_Type_Coop_Federated_Full_Service_10", "Coop Federated ", "None"),
        Row(
            "Cmp_Ban_Type_Coppas_Fresh_Market_Full_Service_10",
            "Coppas Fresh Market ",
            "None",
        ),
        Row("Cmp_Ban_Type_Costco_Canada_0_10", "Costco", "1"),
        Row("Cmp_Ban_Type_Costco_Canada_Discount_10", "Costco Discount", "1"),
        Row("Cmp_Ban_Type_Costco_Canada_Quebec_10", "Costco - Quebec", "None"),
        Row("Cmp_Ban_Type_Country_Grocer_Full_Service_10", "Country Grocer ", "None"),
        Row("Cmp_Ban_Type_Fairway_Markets_Full_Service_10", "Fairway Markets ", "None"),
        Row("Cmp_Ban_Type_Family_Foods_Full_Service_10", "Family Foods ", "None"),
        Row("Cmp_Ban_Type_Fruiticana_Full_Service_10", "Fruiticana ", "None"),
        Row("Cmp_Ban_Type_Fruiticana_Quebec_10", "Fruiticana - Quebec", "None"),
        Row("Cmp_Ban_Type_Giant_Tiger_Stores_Ltd_0_10", "Giant Tiger Stores", "None"),
        Row(
            "Cmp_Ban_Type_Giant_Tiger_Stores_Ltd_Discount_10",
            "Giant Tiger Stores",
            "None",
        ),
        Row(
            "Cmp_Ban_Type_Giant_Tiger_Stores_Ltd_Full_Service_10",
            "Giant Tiger Stores",
            "None",
        ),
        Row(
            "Cmp_Ban_Type_Giant_Tiger_Stores_Ltd_Quebec_10",
            "Giant Tiger Stores - Quebec",
            "None",
        ),
        Row("Cmp_Ban_Type_Goodness_Me_Full_Service_10", "Goodness Me ", "None"),
        Row("Cmp_Ban_Type_Hanahreum_Mart_Full_Service_10", "Hanahreum Mart", "None"),
        Row("Cmp_Ban_Type_Healthy_Planet_Full_Service_10", "Healthy Planet", "None"),
        Row("Cmp_Ban_Type_Highland_Farms_Full_Service_10", "Highland Farms", "None"),
        Row("Cmp_Ban_Type_Hy_Louie_0_10", "Hy Louie", "None"),
        Row("Cmp_Ban_Type_Hy_Louie_Full_Service_10", "Hy Louie", "None"),
        Row(
            "Cmp_Ban_Type_Kins_Farm_Market_Full_Service_10", "Kins Farm Market", "None"
        ),
        Row("Cmp_Ban_Type_Loblaw_0_10", "Loblaw", "None"),
        Row("Cmp_Ban_Type_Loblaw_Discount_10", "Loblaw - Discount", "1"),
        Row("Cmp_Ban_Type_Loblaw_Full_Service_10", "Loblaw - Full Service", "1"),
        Row("Cmp_Ban_Type_Loblaw_Other_10", "Loblaw", "None"),
        Row("Cmp_Ban_Type_Loblaw_Quebec_10", "Loblaw - Quebec", "None"),
        Row("Cmp_Ban_Type_Metro_Inc_0_10", "Metro", "None"),
        Row("Cmp_Ban_Type_Metro_Inc_Discount_10", "Metro - Discount", "1"),
        Row("Cmp_Ban_Type_Metro_Inc_Full_Service_10", "Metro - Full Service", "1"),
        Row("Cmp_Ban_Type_Metro_Inc_Quebec_10", "Metro - Quebec", "None"),
        Row(
            "Cmp_Ban_Type_Nutters_Everyday_Naturals_Full_Service_10",
            "Nutters Everyday Naturals",
            "None",
        ),
        Row(
            "Cmp_Ban_Type_Oceans_Fresh_Food_Market_Inc_Full_Service_10",
            "Oceans Fresh Food Market",
            "None",
        ),
        Row("Cmp_Ban_Type_Organic_Garage_Full_Service_10", "Organic Garage", "None"),
        Row("Cmp_Ban_Type_Other_0_10", "Other", "None"),
        Row("Cmp_Ban_Type_Other_Discount_10", "Other - Discount", "None"),
        Row("Cmp_Ban_Type_Other_Full_Service_10", "Other ", "None"),
        Row("Cmp_Ban_Type_Other_Other_10", "Other", "None"),
        Row("Cmp_Ban_Type_Other_Quebec_10", "Other - Quebec", "None"),
        Row("Cmp_Ban_Type_Overwaitea_Food_Group_0_10", "Overwaitea Food Group", "None"),
        Row(
            "Cmp_Ban_Type_Overwaitea_Food_Group_Full_Service_10",
            "Overwaitea Food Group",
            "None",
        ),
        Row("Cmp_Ban_Type_Rabba_Fine_Foods_0_10", "Rabba Fine Foods", "None"),
        Row(
            "Cmp_Ban_Type_Rabba_Fine_Foods_Full_Service_10", "Rabba Fine Foods", "None"
        ),
        Row(
            "Cmp_Ban_Type_Starsky_Fine_Foods_Full_Service_10",
            "Starsky Fine Foods",
            "None",
        ),
        Row("Cmp_Ban_Type_Sunny_Group_Full_Service_10", "Sunny Group", "None"),
        Row("Cmp_Ban_Type_Sunterra_Market_0_10", "Sunterra Market", "None"),
        Row("Cmp_Ban_Type_Sunterra_Market_Full_Service_10", "Sunterra Market", "None"),
        Row("Cmp_Ban_Type_Unknown_0_10", "Unknown", "None"),
        Row("Cmp_Ban_Type_Unknown_Other_10", "Unknown", "None"),
        Row("Cmp_Ban_Type_Vinces_Market_Full_Service_10", "Vinces Market", "None"),
        Row("Cmp_Ban_Type_Walmart_Inc_Discount_10", "Walmart ", "1"),
        Row("Cmp_Ban_Type_Walmart_Inc_Quebec_10", "Walmart - Quebec", "1"),
        Row("Cmp_Parent_Co_49Th_Parallel_Grocery_10", "49th Parallel", "None"),
        Row("Cmp_Parent_Co_Amazon_Inc_10", "Wholefoods ", "None"),
        Row("Cmp_Parent_Co_Avril_Ss_10", "Avril S", "None"),
        Row("Cmp_Parent_Co_Clover_Farm_10", "Clover Farm ", "None"),
        Row("Cmp_Parent_Co_Coleman_Group_10", "Coleman ", "None"),
        Row("Cmp_Parent_Co_Coop_Atlantic_10", "Coop Atl ", "None"),
        Row("Cmp_Parent_Co_Coop_Federated_10", "Coop Federated", "None"),
        Row("Cmp_Parent_Co_Coppas_Fresh_Market_10", "Coppas Fresh Market ", "None"),
        Row("Cmp_Parent_Co_Costco_Canada_10", "Costco", "None"),
        Row("Cmp_Parent_Co_Country_Grocer_10", "Country Grocer ", "None"),
        Row("Cmp_Parent_Co_Fairway_Markets_10", "Fairway Markets ", "None"),
        Row("Cmp_Parent_Co_Family_Foods_10", "Family Foods ", "None"),
        Row("Cmp_Parent_Co_Fruiticana_10", "Fruiticana ", "None"),
        Row("Cmp_Parent_Co_Giant_Tiger_Stores_Ltd_10", "Giant Tiger Stores", "None"),
        Row("Cmp_Parent_Co_Goodness_Me_10", "Goodness Me ", "None"),
        Row("Cmp_Parent_Co_Hanahreum_Mart_10", "Hanahreum Mart", "None"),
        Row("Cmp_Parent_Co_Healthy_Planet_10", "Healthy Planet", "None"),
        Row("Cmp_Parent_Co_Highland_Farms_10", "Highland Farms", "None"),
        Row("Cmp_Parent_Co_Hy_Louie_10", "Hy Louie", "None"),
        Row("Cmp_Parent_Co_Kins_Farm_Market_10", "Kins Farm Market", "None"),
        Row("Cmp_Parent_Co_Loblaw_10", "Loblaw", "None"),
        Row("Cmp_Parent_Co_Metro_Inc_10", "Metro", "None"),
        Row(
            "Cmp_Parent_Co_Nutters_Everyday_Naturals_10",
            "Nutters Everyday Naturals",
            "None",
        ),
        Row(
            "Cmp_Parent_Co_Oceans_Fresh_Food_Market_Inc_10",
            "Oceans Fresh Food Market",
            "None",
        ),
        Row("Cmp_Parent_Co_Organic_Garage_10", "Organic Garage", "None"),
        Row("Cmp_Parent_Co_Other_10", "Other", "None"),
        Row("Cmp_Parent_Co_Overwaitea_Food_Group_10", "Overwaitea Food Group", "None"),
        Row("Cmp_Parent_Co_Rabba_Fine_Foods_10", "Rabba Fine Foods", "None"),
        Row("Cmp_Parent_Co_Starsky_Fine_Foods_10", "Starsky Fine Foods", "None"),
        Row("Cmp_Parent_Co_Sunny_Group_10", "Sunny Group", "None"),
        Row("Cmp_Parent_Co_Sunterra_Market_10", "Sunterra Market", "None"),
        Row("Cmp_Parent_Co_Unknown_10", "Unknown", "None"),
        Row("Cmp_Parent_Co_Vinces_Market_10", "Vinces Market", "None"),
        Row("Cmp_Parent_Co_Walmart_Inc_10", "Walmart ", "None"),
        Row("Cmp_Segment_0_10", "Total Segment Competitors", "1"),
        Row("Cmp_Segment_Discount_10", "Total Discount Competitors", "1"),
        Row("Cmp_Segment_Full_Service_10", "Total Full Service Competitors", "1"),
        Row("Cmp_Segment_Other_10", "Total Other Competitors", "None"),
        Row("Cmp_Segment_Quebec_10", "Total Quebec Competitors", "None"),
        Row("Cmp_Store_Cnt_10", "Total Competitors", "1"),
    ]
).toDF(["var_details", "Cmp Feature", "Flag"])
