from pyspark import Row

from tests.utils.spark_util import spark_tests as spark

DF_FINAL_NEED_STATES = spark.createDataFrame(
    [
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenHandhelds",
            ITEM_NO="375074",
            need_state="-1",
            ITEM_NAME="Delissio Rsnc 4 Cheese",
            ITEM_SK="14527712",
            LVL5_NAME="Rising Crust Pizza",
            LVL5_ID="303-04-20",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenHandhelds",
            ITEM_NO="633928",
            need_state="0",
            ITEM_NAME="DrOetker CasaMamaPizzaPulldPrk",
            ITEM_SK="15954718",
            LVL5_NAME="Rising Crust Pizza",
            LVL5_ID="303-04-20",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenPizza",
            ITEM_NO="164849",
            need_state="-1",
            ITEM_NAME="DrOetker CasaMama Pizza Deluxe",
            ITEM_SK="11624934",
            LVL5_NAME="Rising Crust Pizza",
            LVL5_ID="303-04-20",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenPizza",
            ITEM_NO="375030",
            need_state="3",
            ITEM_NAME="Delisso Pzria Deluxe",
            ITEM_SK="14527707",
            LVL5_NAME="Traditional Crust Pizza",
            LVL5_ID="303-04-22",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenPizza",
            ITEM_NO="819649",
            need_state="2",
            ITEM_NAME="DrOetker Pizza RiCrust 4Cheese",
            ITEM_SK="16967264",
            LVL5_NAME="Rising Crust Pizza",
            LVL5_ID="303-04-20",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenPizza",
            ITEM_NO="955963",
            need_state="1",
            ITEM_NAME="Delissio Pizza StuffedCrst Pep",
            ITEM_SK="17413471",
            LVL5_NAME="Rising Crust Pizza",
            LVL5_ID="303-04-20",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenPizza",
            ITEM_NO="678984",
            need_state="2",
            ITEM_NAME="DrOetker Pza CasaDMa ClsscCdn",
            ITEM_SK="16382236",
            LVL5_NAME="Thin Crust Pizza",
            LVL5_ID="303-04-21",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenPizza",
            ITEM_NO="375039",
            need_state="1",
            ITEM_NAME="Delissio RsnC Peprn 12IN",
            ITEM_SK="14527708",
            LVL5_NAME="Rising Crust Pizza",
            LVL5_ID="303-04-20",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenHandhelds",
            ITEM_NO="265836",
            need_state="1",
            ITEM_NAME="DrOetker Ristornt Pollo Pizza",
            ITEM_SK="12148092",
            LVL5_NAME="Thin Crust Pizza",
            LVL5_ID="303-04-21",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenHandhelds",
            ITEM_NO="541805",
            need_state="1",
            ITEM_NAME="DrOetKer Giusep Thin Crst Spin",
            ITEM_SK="18305394",
            LVL5_NAME="Thin Crust Pizza",
            LVL5_ID="303-04-21",
            LVL2_ID="M33",
            LVL3_ID="M330",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ice Cream and Dessert",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenHandhelds",
            ITEM_NO="413819",
            need_state="-1",
            ITEM_NAME="DrOetker Ristornt T/Crst PzVeg",
            ITEM_SK="11676176",
            LVL5_NAME="Thin Crust Pizza",
            LVL5_ID="303-04-21",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenHandhelds",
            ITEM_NO="375044",
            need_state="-1",
            ITEM_NAME="Delissio Rsnc Deluxe 12IN",
            ITEM_SK="14527709",
            LVL5_NAME="Rising Crust Pizza",
            LVL5_ID="303-04-20",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenPizza",
            ITEM_NO="314792",
            need_state="-1",
            ITEM_NAME="DrOetker Pizza Pepperoni Pesto",
            ITEM_SK="13956702",
            LVL5_NAME="Thin Crust Pizza",
            LVL5_ID="303-04-21",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenHandhelds",
            ITEM_NO="576782",
            need_state="0",
            ITEM_NAME="DrOetker Glusep Thin Can  510g",
            ITEM_SK="15779355",
            LVL5_NAME="Thin Crust Pizza",
            LVL5_ID="303-04-21",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            EXEC_ID="ontario_SOBEYS_FrozenPizza",
            ITEM_NO="900100",
            need_state="-1",
            ITEM_NAME="SMI Opsite 24632 Dr 5x5in  1ea",
            ITEM_SK="17182217",
            LVL5_NAME="Garlic Fingers",
            LVL5_ID="303-04-24",
            LVL2_ID="M33",
            LVL3_ID="M3304",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            CATEGORY_ID="33-04-01",
            cannib_id="CANNIB-930",
            REGION="ontario",
            NATIONAL_BANNER_DESC="SOBEYS",
            SECTION_MASTER="Frozen Pizza",
        ),
    ]
)
