from tests.utils.spark_util import spark_tests as spark

from pyspark import Row


"""
from spaceprod.utils.space_context import context
from tests.mock_data.location import DF_LOCATION
run = "dbfs:/mnt/blob/sobeys_space_prod/space_run_20220120_022927_742761_3x3_negotiations_copy" # Dominics breaking run on opt post proc
context.reload_context_from_run_folder(run)
d=context.data.read("localized_default_space")
df_scope = DF_LOCATION.select("store_no").dropDuplicates()
d = d.join(df_scope, "store_no", "inner")
print(df_to_ddl(d,"DF_LOCALIZED_DEFAULT_SPACE"))
"""


DF_LOCALIZED_DEFAULT_SPACE = spark.createDataFrame(
    [
        Row(
            store_no="649",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NATURAL HOT BEVERAGES",
            total_space="863.1799999999995",
            local_total_space="12.6",
        ),
        Row(
            store_no="851",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="OIL & VINEGAR",
            total_space="856.3500000000003",
            local_total_space="5.68",
        ),
        Row(
            store_no="7314",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="SOFT DRINKS",
            total_space="3337.4400000000023",
            local_total_space="10.55",
        ),
        Row(
            store_no="685",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NATURAL JUICES",
            total_space="658.04",
            local_total_space="7.86",
        ),
        Row(
            store_no="4747",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="FLOUR AND SUGAR",
            total_space="852.5399999999998",
            local_total_space="4.78",
        ),
        Row(
            store_no="657",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="FEMININE HYGIENE",
            total_space="1198.0199999999998",
            local_total_space="6.3",
        ),
        Row(
            store_no="7383",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="HAIRCOLOUR",
            total_space="828.4599999999991",
            local_total_space="71.61999999999999",
        ),
        Row(
            store_no="7383",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="SKIN CARE",
            total_space="693.8300000000004",
            local_total_space="9.350000000000001",
        ),
        Row(
            store_no="7331",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="WASTE",
            total_space="294.99",
            local_total_space="11.19",
        ),
        Row(
            store_no="4719",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="SOUTH ASIAN",
            total_space="2237.9599999999996",
            local_total_space="92.32000000000001",
        ),
        Row(
            store_no="4719",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="OIL & VINEGAR",
            total_space="856.3500000000005",
            local_total_space="5.68",
        ),
        Row(
            store_no="678",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="SOFT DRINKS",
            total_space="3258.390000000005",
            local_total_space="15.7",
        ),
        Row(
            store_no="899",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="SKIN CARE",
            total_space="604.6799999999996",
            local_total_space="5.0",
        ),
        Row(
            store_no="694",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="HAIR CARE",
            total_space="1709.35",
            local_total_space="7.0",
        ),
        Row(
            store_no="694",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="FEMININE HYGIENE",
            total_space="1419.0000000000002",
            local_total_space="4.0",
        ),
        Row(
            store_no="6713",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="SKIN CARE",
            total_space="693.8299999999999",
            local_total_space="2.7",
        ),
        Row(
            store_no="4726",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="SOFT DRINKS",
            total_space="2290.420000000001",
            local_total_space="15.7",
        ),
        Row(
            store_no="4726",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="EGGS",
            total_space="420.40000000000003",
            local_total_space="11.8",
        ),
        Row(
            store_no="935",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NATURAL JUICES",
            total_space="993.6100000000001",
            local_total_space="8.55",
        ),
        Row(
            store_no="873",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NATURAL CONDIMENTS",
            total_space="496.46999999999986",
            local_total_space="6.0",
        ),
        Row(
            store_no="873",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NATURAL HOT BEVERAGES",
            total_space="573.35",
            local_total_space="3.9",
        ),
        Row(
            store_no="922",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="SOUTH ASIAN",
            total_space="1648.5400000000002",
            local_total_space="94.53",
        ),
        Row(
            store_no="4748",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NATURAL CONDIMENTS",
            total_space="496.4700000000001",
            local_total_space="3.9",
        ),
        Row(
            store_no="777",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NATURAL JUICES",
            total_space="583.4499999999999",
            local_total_space="5.7",
        ),
        Row(
            store_no="742",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="ORAL CARE",
            total_space="1738.5200000000011",
            local_total_space="6.5",
        ),
        Row(
            store_no="938",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="FLOUR AND SUGAR",
            total_space="852.54",
            local_total_space="4.78",
        ),
        Row(
            store_no="7380",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="SOUTH ASIAN",
            total_space="1783.3099999999995",
            local_total_space="90.53",
        ),
        Row(
            store_no="7380",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="HOUSEHOLD CLEANERS",
            total_space="1125.9600000000007",
            local_total_space="4.2",
        ),
        Row(
            store_no="852",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NATURAL HOT BEVERAGES",
            total_space="602.5999999999999",
            local_total_space="12.6",
        ),
        Row(
            store_no="852",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="HAIRCOLOUR",
            total_space="823.5899999999993",
            local_total_space="81.90999999999998",
        ),
        Row(
            store_no="639",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NATURAL HOT BEVERAGES",
            total_space="1003.1499999999996",
            local_total_space="15.6",
        ),
        Row(
            store_no="639",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="SKIN CARE",
            total_space="693.8300000000003",
            local_total_space="2.88",
        ),
        Row(
            store_no="7496",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="ENERGY BARS",
            total_space="712.2500000000001",
            local_total_space="6.25",
        ),
        Row(
            store_no="7496",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="FRUIT CUPS",
            total_space="503.13999999999993",
            local_total_space="8.32",
        ),
        Row(
            store_no="4729",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="AP/DEO",
            total_space="552.9900000000001",
            local_total_space="1.95",
        ),
        Row(
            store_no="4729",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NATURAL PASTA/SAUCE",
            total_space="992.5600000000007",
            local_total_space="10.1",
        ),
        Row(
            store_no="715",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NATURAL HOT BEVERAGES",
            total_space="669.46",
            local_total_space="10.2",
        ),
        Row(
            store_no="715",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="FLOUR AND SUGAR",
            total_space="852.5399999999995",
            local_total_space="5.6",
        ),
        Row(
            store_no="715",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NATURAL PASTA/SAUCE",
            total_space="648.2500000000005",
            local_total_space="10.1",
        ),
        Row(
            store_no="715",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NATURAL CONDIMENTS",
            total_space="286.5799999999999",
            local_total_space="3.42",
        ),
        Row(
            store_no="641",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="NON CARB BEVERAGES (NCB)",
            total_space="569.5500000000001",
            local_total_space="15.299999999999999",
        ),
        Row(
            store_no="709",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="DOG FOOD DRY",
            total_space="1710.7200000000003",
            local_total_space="14.9",
        ),
        Row(
            store_no="709",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="AP/DEO",
            total_space="617.0499999999998",
            local_total_space="3.9",
        ),
        Row(
            store_no="925",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="HAIRCOLOUR",
            total_space="560.2299999999994",
            local_total_space="6.75",
        ),
        Row(
            store_no="925",
            region_desc="Ontario",
            national_banner_desc="SOBEYS",
            section_master="EGGS",
            total_space="630.33",
            local_total_space="11.74",
        ),
    ]
)
