from pyspark import Row

from tests.utils.spark_util import spark_tests as spark

DF_MAPPING = spark.createDataFrame(
    [
        Row(Feature="2020_Total_Population_5", Denominator="None"),
        Row(Feature="2020_Total_Census_Family_Households_5", Denominator="None"),
        Row(
            Feature="2020_In_The_Labour_Force_5", Denominator="2020_Total_Population_5"
        ),
        Row(
            Feature="2020_Total_Population_0_To_4_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_5_To_9_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_10_To_14_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_15_To_19_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_20_To_24_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_25_To_29_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_30_To_34_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_35_To_39_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_40_To_44_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_45_To_49_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_50_To_54_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_55_To_59_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_60_To_64_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_65_To_69_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_70_To_74_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_75_To_79_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_80_To_84_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(
            Feature="2020_Total_Population_85_Or_Older_5",
            Denominator="2020_Total_Population_5",
        ),
        Row(Feature="2020_Average_Age_Of_Total_Population_5", Denominator="None"),
        Row(Feature="2020_Total_Households_For_Household_Size_5", Denominator="None"),
        Row(
            Feature="2020_Household_Size_Average_Number_Of_Persons_In_Private_Households_5",
            Denominator="None",
        ),
        Row(Feature="2020_Total_Number_Of_Children_At_Home_5", Denominator="None"),
        Row(Feature="2020_Average_Children_Per_Household_5", Denominator="None"),
        Row(
            Feature="2020_Household_Income_0_To_19999_Current_Year__5",
            Denominator="2020_Total_Households_For_Household_Size_5",
        ),
        Row(
            Feature="2020_Household_Income_20000_To_39999_Current_Year__5",
            Denominator="2020_Total_Households_For_Household_Size_5",
        ),
        Row(
            Feature="2020_Household_Income_40000_To_59999_Current_Year__5",
            Denominator="2020_Total_Households_For_Household_Size_5",
        ),
        Row(
            Feature="2020_Household_Income_60000_To_79999_Current_Year__5",
            Denominator="2020_Total_Households_For_Household_Size_5",
        ),
        Row(
            Feature="2020_Household_Income_80000_To_99999_Current_Year__5",
            Denominator="2020_Total_Households_For_Household_Size_5",
        ),
        Row(
            Feature="2020_Household_Income_100000_Or_Over_Current_Year__5",
            Denominator="2020_Total_Households_For_Household_Size_5",
        ),
        Row(
            Feature="2020_Household_Income_100000_To_124999_Current_Year__5",
            Denominator="2020_Total_Households_For_Household_Size_5",
        ),
        Row(
            Feature="2020_Household_Income_125000_To_149999_Current_Year__5",
            Denominator="2020_Total_Households_For_Household_Size_5",
        ),
        Row(
            Feature="2020_Household_Income_150000_To_199999_Current_Year__5",
            Denominator="2020_Total_Households_For_Household_Size_5",
        ),
        Row(
            Feature="2020_Household_Income_200000_Or_Over_Current_Year__5",
            Denominator="2020_Total_Households_For_Household_Size_5",
        ),
        Row(
            Feature="2020_Household_Income_200000_To_299999_Current_Year__5",
            Denominator="2020_Total_Households_For_Household_Size_5",
        ),
        Row(
            Feature="2020_Household_Income_300000_Or_Over_Current_Year__5",
            Denominator="2020_Total_Households_For_Household_Size_5",
        ),
        Row(
            Feature="2020_Average_Household_Income_Current_Year__5", Denominator="None"
        ),
        Row(Feature="2020_Median_Household_Income_Current_Year__5", Denominator="None"),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_5",
            Denominator="None",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_No_Certificate_Diploma_Or_Degree_5",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_5",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_High_School_Certificate_Or_Equivalent_5",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_5",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_Apprenticeship_Or_Trades_Certificate_Or_Diploma_5",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_5",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_College_Cegep_Or_Other_Nonuniversity_Certificate_Or_Diploma_5",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_5",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_University_Certificate_Or_Diploma_Below_Bachelor_5",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_5",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_University_Degree_5",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_5",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_Bachelors_Degree_5",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_5",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_Above_Bachelors_5",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Visible_Minority_5",
            Denominator="None",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Chinese_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_South_Asian_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Black_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Filipino_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Latin_American_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Southeast_Asian_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Arab_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_West_Asian_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Korean_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Japanese_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_All_Other_Visible_Minorities_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_Multiple_Visible_Minorities_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_Not_A_Visible_Minority_5",
            Denominator="2020_Household_Population_For_Visible_Minority_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
            Denominator="None",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_In_Province_Of_Birth_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_Outside_Province_Of_Birth_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Total_Immigrant_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Americas_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_North_America_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_United_States_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Central_America_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_El_Salvador_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Mexico_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Caribbean_And_Bermuda_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Cuba_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Haiti_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Jamaica_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Trinidad_And_Tobago_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_South_America_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Brazil_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Chile_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Colombia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Guyana_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Peru_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Venezuela_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Europe_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Western_Europe_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_France_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Germany_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Netherlands_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Eastern_Europe_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Czech_Republic_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Hungary_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Moldova_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Poland_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Romania_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Russia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Ukraine_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Northern_Europe_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_United_Kingdom_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Ireland_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Southern_Europe_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Greece_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Italy_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Portugal_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Bosnia_Herzegovina_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Croatia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Serbia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Africa_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Western_Africa_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Cte_Divoire_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Ghana_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nigeria_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Eastern_Africa_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Eritrea_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Ethiopia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Kenya_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Somalia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Tanzania_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Central_Africa_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Cameroon_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Congo_The_Democratic_Republic_Of_The_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Northern_Africa_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Algeria_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Egypt_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Morocco_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Tunisia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Southern_Africa_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_South_Africa_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Asia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_West_Central_Asia_And_Middle_East_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Afghanistan_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Iran_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Iraq_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Israel_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Lebanon_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Saudi_Arabia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Syria_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Turkey_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_United_Arab_Emirates_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Eastern_Asia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_China_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Hong_Kong_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Japan_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_South_Korea_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Taiwan_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Southeastern_Asia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Cambodia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Malaysia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Philippines_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Vietnam_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Southern_Asia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Bangladesh_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_India_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nepal_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Pakistan_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Sri_Lanka_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Australia_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Fiji_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonpermanent_Residents_5",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_5",
        ),
        Row(Feature="2020_Total_Population_10", Denominator="None"),
        Row(Feature="2020_Total_Census_Family_Households_10", Denominator="None"),
        Row(
            Feature="2020_In_The_Labour_Force_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_0_To_4_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_5_To_9_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_10_To_14_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_15_To_19_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_20_To_24_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_25_To_29_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_30_To_34_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_35_To_39_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_40_To_44_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_45_To_49_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_50_To_54_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_55_To_59_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_60_To_64_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_65_To_69_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_70_To_74_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_75_To_79_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_80_To_84_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(
            Feature="2020_Total_Population_85_Or_Older_10",
            Denominator="2020_Total_Population_10",
        ),
        Row(Feature="2020_Average_Age_Of_Total_Population_10", Denominator="None"),
        Row(Feature="2020_Total_Households_For_Household_Size_10", Denominator="None"),
        Row(
            Feature="2020_Household_Size_Average_Number_Of_Persons_In_Private_Households_10",
            Denominator="None",
        ),
        Row(Feature="2020_Total_Number_Of_Children_At_Home_10", Denominator="None"),
        Row(Feature="2020_Average_Children_Per_Household_10", Denominator="None"),
        Row(
            Feature="2020_Household_Income_0_To_19999_Current_Year__10",
            Denominator="2020_Total_Households_For_Household_Size_10",
        ),
        Row(
            Feature="2020_Household_Income_20000_To_39999_Current_Year__10",
            Denominator="2020_Total_Households_For_Household_Size_10",
        ),
        Row(
            Feature="2020_Household_Income_40000_To_59999_Current_Year__10",
            Denominator="2020_Total_Households_For_Household_Size_10",
        ),
        Row(
            Feature="2020_Household_Income_60000_To_79999_Current_Year__10",
            Denominator="2020_Total_Households_For_Household_Size_10",
        ),
        Row(
            Feature="2020_Household_Income_80000_To_99999_Current_Year__10",
            Denominator="2020_Total_Households_For_Household_Size_10",
        ),
        Row(
            Feature="2020_Household_Income_100000_Or_Over_Current_Year__10",
            Denominator="2020_Total_Households_For_Household_Size_10",
        ),
        Row(
            Feature="2020_Household_Income_100000_To_124999_Current_Year__10",
            Denominator="2020_Total_Households_For_Household_Size_10",
        ),
        Row(
            Feature="2020_Household_Income_125000_To_149999_Current_Year__10",
            Denominator="2020_Total_Households_For_Household_Size_10",
        ),
        Row(
            Feature="2020_Household_Income_150000_To_199999_Current_Year__10",
            Denominator="2020_Total_Households_For_Household_Size_10",
        ),
        Row(
            Feature="2020_Household_Income_200000_Or_Over_Current_Year__10",
            Denominator="2020_Total_Households_For_Household_Size_10",
        ),
        Row(
            Feature="2020_Household_Income_200000_To_299999_Current_Year__10",
            Denominator="2020_Total_Households_For_Household_Size_10",
        ),
        Row(
            Feature="2020_Household_Income_300000_Or_Over_Current_Year__10",
            Denominator="2020_Total_Households_For_Household_Size_10",
        ),
        Row(
            Feature="2020_Average_Household_Income_Current_Year__10", Denominator="None"
        ),
        Row(
            Feature="2020_Median_Household_Income_Current_Year__10", Denominator="None"
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_10",
            Denominator="None",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_No_Certificate_Diploma_Or_Degree_10",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_10",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_High_School_Certificate_Or_Equivalent_10",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_10",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_Apprenticeship_Or_Trades_Certificate_Or_Diploma_10",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_10",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_College_Cegep_Or_Other_Nonuniversity_Certificate_Or_Diploma_10",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_10",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_University_Certificate_Or_Diploma_Below_Bachelor_10",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_10",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_University_Degree_10",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_10",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_Bachelors_Degree_10",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_10",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_Above_Bachelors_10",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Visible_Minority_10",
            Denominator="None",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Chinese_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_South_Asian_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Black_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Filipino_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Latin_American_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Southeast_Asian_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Arab_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_West_Asian_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Korean_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Japanese_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_All_Other_Visible_Minorities_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_Multiple_Visible_Minorities_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_Not_A_Visible_Minority_10",
            Denominator="2020_Household_Population_For_Visible_Minority_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
            Denominator="None",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_In_Province_Of_Birth_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_Outside_Province_Of_Birth_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Total_Immigrant_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Americas_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_North_America_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_United_States_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Central_America_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_El_Salvador_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Mexico_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Caribbean_And_Bermuda_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Cuba_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Haiti_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Jamaica_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Trinidad_And_Tobago_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_South_America_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Brazil_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Chile_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Colombia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Guyana_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Peru_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Venezuela_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Europe_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Western_Europe_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_France_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Germany_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Netherlands_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Eastern_Europe_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Czech_Republic_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Hungary_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Moldova_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Poland_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Romania_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Russia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Ukraine_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Northern_Europe_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_United_Kingdom_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Ireland_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Southern_Europe_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Greece_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Italy_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Portugal_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Bosnia_Herzegovina_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Croatia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Serbia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Africa_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Western_Africa_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Cte_Divoire_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Ghana_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nigeria_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Eastern_Africa_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Eritrea_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Ethiopia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Kenya_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Somalia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Tanzania_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Central_Africa_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Cameroon_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Congo_The_Democratic_Republic_Of_The_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Northern_Africa_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Algeria_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Egypt_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Morocco_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Tunisia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Southern_Africa_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_South_Africa_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Asia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_West_Central_Asia_And_Middle_East_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Afghanistan_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Iran_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Iraq_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Israel_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Lebanon_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Saudi_Arabia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Syria_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Turkey_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_United_Arab_Emirates_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Eastern_Asia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_China_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Hong_Kong_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Japan_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_South_Korea_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Taiwan_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Southeastern_Asia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Cambodia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Malaysia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Philippines_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Vietnam_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Southern_Asia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Bangladesh_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_India_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nepal_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Pakistan_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Sri_Lanka_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Australia_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Fiji_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonpermanent_Residents_10",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_10",
        ),
        Row(Feature="2020_Total_Population_15", Denominator="None"),
        Row(Feature="2020_Total_Census_Family_Households_15", Denominator="None"),
        Row(
            Feature="2020_In_The_Labour_Force_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_0_To_4_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_5_To_9_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_10_To_14_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_15_To_19_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_20_To_24_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_25_To_29_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_30_To_34_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_35_To_39_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_40_To_44_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_45_To_49_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_50_To_54_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_55_To_59_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_60_To_64_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_65_To_69_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_70_To_74_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_75_To_79_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_80_To_84_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(
            Feature="2020_Total_Population_85_Or_Older_15",
            Denominator="2020_Total_Population_15",
        ),
        Row(Feature="2020_Average_Age_Of_Total_Population_15", Denominator="None"),
        Row(Feature="2020_Total_Households_For_Household_Size_15", Denominator="None"),
        Row(
            Feature="2020_Household_Size_Average_Number_Of_Persons_In_Private_Households_15",
            Denominator="None",
        ),
        Row(Feature="2020_Total_Number_Of_Children_At_Home_15", Denominator="None"),
        Row(Feature="2020_Average_Children_Per_Household_15", Denominator="None"),
        Row(
            Feature="2020_Household_Income_0_To_19999_Current_Year__15",
            Denominator="2020_Total_Households_For_Household_Size_15",
        ),
        Row(
            Feature="2020_Household_Income_20000_To_39999_Current_Year__15",
            Denominator="2020_Total_Households_For_Household_Size_15",
        ),
        Row(
            Feature="2020_Household_Income_40000_To_59999_Current_Year__15",
            Denominator="2020_Total_Households_For_Household_Size_15",
        ),
        Row(
            Feature="2020_Household_Income_60000_To_79999_Current_Year__15",
            Denominator="2020_Total_Households_For_Household_Size_15",
        ),
        Row(
            Feature="2020_Household_Income_80000_To_99999_Current_Year__15",
            Denominator="2020_Total_Households_For_Household_Size_15",
        ),
        Row(
            Feature="2020_Household_Income_100000_Or_Over_Current_Year__15",
            Denominator="2020_Total_Households_For_Household_Size_15",
        ),
        Row(
            Feature="2020_Household_Income_100000_To_124999_Current_Year__15",
            Denominator="2020_Total_Households_For_Household_Size_15",
        ),
        Row(
            Feature="2020_Household_Income_125000_To_149999_Current_Year__15",
            Denominator="2020_Total_Households_For_Household_Size_15",
        ),
        Row(
            Feature="2020_Household_Income_150000_To_199999_Current_Year__15",
            Denominator="2020_Total_Households_For_Household_Size_15",
        ),
        Row(
            Feature="2020_Household_Income_200000_Or_Over_Current_Year__15",
            Denominator="2020_Total_Households_For_Household_Size_15",
        ),
        Row(
            Feature="2020_Household_Income_200000_To_299999_Current_Year__15",
            Denominator="2020_Total_Households_For_Household_Size_15",
        ),
        Row(
            Feature="2020_Household_Income_300000_Or_Over_Current_Year__15",
            Denominator="2020_Total_Households_For_Household_Size_15",
        ),
        Row(
            Feature="2020_Average_Household_Income_Current_Year__15", Denominator="None"
        ),
        Row(
            Feature="2020_Median_Household_Income_Current_Year__15", Denominator="None"
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_15",
            Denominator="None",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_No_Certificate_Diploma_Or_Degree_15",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_15",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_High_School_Certificate_Or_Equivalent_15",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_15",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_Apprenticeship_Or_Trades_Certificate_Or_Diploma_15",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_15",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_College_Cegep_Or_Other_Nonuniversity_Certificate_Or_Diploma_15",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_15",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_University_Certificate_Or_Diploma_Below_Bachelor_15",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_15",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_University_Degree_15",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_15",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_Bachelors_Degree_15",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_15",
        ),
        Row(
            Feature="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_Above_Bachelors_15",
            Denominator="2020_Household_Population_15_Years_Or_Over_For_Educational_Attainment_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Visible_Minority_15",
            Denominator="None",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Chinese_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_South_Asian_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Black_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Filipino_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Latin_American_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Southeast_Asian_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Arab_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_West_Asian_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Korean_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_Total_Visible_Minorities_Japanese_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_All_Other_Visible_Minorities_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_Multiple_Visible_Minorities_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_Not_A_Visible_Minority_15",
            Denominator="2020_Household_Population_For_Visible_Minority_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
            Denominator="None",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_In_Province_Of_Birth_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_Outside_Province_Of_Birth_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Total_Immigrant_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Americas_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_North_America_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_United_States_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Central_America_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_El_Salvador_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Mexico_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Caribbean_And_Bermuda_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Cuba_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Haiti_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Jamaica_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Trinidad_And_Tobago_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_South_America_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Brazil_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Chile_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Colombia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Guyana_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Peru_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Venezuela_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Europe_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Western_Europe_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_France_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Germany_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Netherlands_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Eastern_Europe_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Czech_Republic_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Hungary_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Moldova_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Poland_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Romania_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Russia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Ukraine_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Northern_Europe_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_United_Kingdom_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Ireland_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Southern_Europe_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Greece_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Italy_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Portugal_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Bosnia_Herzegovina_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Croatia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Serbia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Africa_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Western_Africa_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Cte_Divoire_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Ghana_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nigeria_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Eastern_Africa_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Eritrea_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Ethiopia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Kenya_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Somalia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Tanzania_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Central_Africa_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Cameroon_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Congo_The_Democratic_Republic_Of_The_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Northern_Africa_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Algeria_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Egypt_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Morocco_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Tunisia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Southern_Africa_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_South_Africa_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Asia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_West_Central_Asia_And_Middle_East_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Afghanistan_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Iran_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Iraq_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Israel_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Lebanon_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Saudi_Arabia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Syria_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Turkey_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_United_Arab_Emirates_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Eastern_Asia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_China_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Hong_Kong_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Japan_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_South_Korea_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Taiwan_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Southeastern_Asia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Cambodia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Malaysia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Philippines_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Vietnam_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Southern_Asia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Bangladesh_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_India_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nepal_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Pakistan_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Sri_Lanka_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Australia_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Fiji_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
        Row(
            Feature="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonpermanent_Residents_15",
            Denominator="2020_Household_Population_For_Total_Immigration_By_Place_Of_Birth_Nonimmigrant_15",
        ),
    ]
)
