from tests.utils.spark_util import spark_tests as spark

from pyspark import Row

"""
from spaceprod.utils.space_context import context

from spaceprod.utils.data_transformation import union_dfs
from tests.mock_data.product import DF_PRODUCT
from tests.mock_data.supplier_item_mapping import DF_SUPPLIER_ITEM_MAPPING

run = "dbfs:/mnt/blob/sobeys_space_prod/space_run_20220120_022927_742761_3x3_negotiations_copy" # Dominics breaking run on opt post proc
context.reload_context_from_run_folder(run)
d=context.data.read("own_brands_path")
df_scope = union_dfs([DF_PRODUCT.select("ITEM_NO"), DF_SUPPLIER_ITEM_MAPPING.select("ITEM_NO")], align_schemas=True).dropDuplicates()
d = d.join(df_scope, "ITEM_NO", "inner")
print(df_to_ddl(d,"DF_OWN_BRANDS"))
"""

DF_OWN_BRANDS = spark.createDataFrame(
    [
        Row(
            ITEM_NO="608841",
            STORE_BRAND_CD="X",
            STORE_BRAND_ENG_DESC="COMPLIMENTS GLUTEN FREE",
        ),
        Row(ITEM_NO="679140", STORE_BRAND_CD="AC", STORE_BRAND_ENG_DESC="EDWARDS"),
        Row(ITEM_NO="760043", STORE_BRAND_CD="AB", STORE_BRAND_ENG_DESC="BEST BUY"),
        Row(
            ITEM_NO="233105",
            STORE_BRAND_CD="L",
            STORE_BRAND_ENG_DESC="COMPLIMENTS SENSATIONAL",
        ),
        Row(ITEM_NO="771935", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="224869", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="589701", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="521203", STORE_BRAND_CD="AB", STORE_BRAND_ENG_DESC="BEST BUY"),
        Row(ITEM_NO="771933", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="760057", STORE_BRAND_CD="AB", STORE_BRAND_ENG_DESC="BEST BUY"),
        Row(ITEM_NO="771919", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="760036", STORE_BRAND_CD="AB", STORE_BRAND_ENG_DESC="BEST BUY"),
        Row(ITEM_NO="758405", STORE_BRAND_CD="AB", STORE_BRAND_ENG_DESC="BEST BUY"),
        Row(ITEM_NO="860124", STORE_BRAND_CD="AC", STORE_BRAND_ENG_DESC="EDWARDS"),
        Row(ITEM_NO="771913", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="860156", STORE_BRAND_CD="AC", STORE_BRAND_ENG_DESC="EDWARDS"),
        Row(ITEM_NO="589696", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="771940", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="860154", STORE_BRAND_CD="AC", STORE_BRAND_ENG_DESC="EDWARDS"),
        Row(
            ITEM_NO="233098",
            STORE_BRAND_CD="L",
            STORE_BRAND_ENG_DESC="COMPLIMENTS SENSATIONAL",
        ),
        Row(ITEM_NO="521211", STORE_BRAND_CD="AB", STORE_BRAND_ENG_DESC="BEST BUY"),
        Row(ITEM_NO="860144", STORE_BRAND_CD="AC", STORE_BRAND_ENG_DESC="EDWARDS"),
        Row(ITEM_NO="151899", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="589683", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="758393", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="771929", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="589851", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="860141", STORE_BRAND_CD="AC", STORE_BRAND_ENG_DESC="EDWARDS"),
        Row(ITEM_NO="171132", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="589811", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="771925", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="758392", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="171131", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="152818", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="860157", STORE_BRAND_CD="AC", STORE_BRAND_ENG_DESC="EDWARDS"),
        Row(
            ITEM_NO="608825",
            STORE_BRAND_CD="X",
            STORE_BRAND_ENG_DESC="COMPLIMENTS GLUTEN FREE",
        ),
        Row(ITEM_NO="589887", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(
            ITEM_NO="282187",
            STORE_BRAND_CD="L",
            STORE_BRAND_ENG_DESC="COMPLIMENTS SENSATIONAL",
        ),
        Row(ITEM_NO="486899", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="229487", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="232134", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="437095", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="229489", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="229490", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="146495", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="375596", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="229480", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="437093", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="229482", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="589890", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="758391", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
        Row(ITEM_NO="771937", STORE_BRAND_CD="C", STORE_BRAND_ENG_DESC="COMPLIMENTS"),
    ]
)
