from pyspark import Row

from tests.utils.spark_util import spark_tests as spark

DF_POG_SECTION_MASTER = spark.createDataFrame(
    [
        Row("DINNERS AND ENTREES 05DR SBY ONT", "Dinners And Entrees"),
        Row("DINNERS AND ENTREES 06DR SBY ONT", "Dinners And Entrees"),
        Row("DINNERS AND ENTREES 07DR SBY ONT", "Dinners And Entrees"),
        Row("DINNERS AND ENTREES 08DR SBY ONT", "Dinners And Entrees"),
        Row("DINNERS AND ENTREES 09DR SBY ONT", "Dinners And Entrees"),
        Row("DINNERS AND ENTREES 10DR SBY ONT", "Dinners And Entrees"),
        Row("DINNERS AND ENTREES 11DR SBY ONT", "Dinners And Entrees"),
        Row("DINNERS AND ENTREES 12DR SBY ONT", "Dinners And Entrees"),
        Row("DINNERS AND ENTREES 13DR SBY ONT", "Dinners And Entrees"),
        Row("DINNERS AND ENTREES 14DR SBY ONT", "Dinners And Entrees"),
        Row("DINNERS AND ENTREES 15DR SBY ONT", "Dinners And Entrees"),
        Row("DINNERS AND ENTREES 16DR SBY ONT", "Dinners And Entrees"),
        Row("FROZEN BREAKFAST 02DR SBY ONT", "Frozen Breakfast"),
        Row("FROZEN BREAKFAST 03DR SBY ONT", "Frozen Breakfast"),
        Row("FROZEN BREAKFAST 04DR SBY ONT", "Frozen Breakfast"),
        Row("FROZEN BREAKFAST 05DR SBY ONT", "Frozen Breakfast"),
        Row("FROZEN BREAKFAST 12FT BNKR SBY ONT", "Frozen Breakfast"),
        Row("FROZEN DESSERT 01DR SB ONT", "Frozen Dessert"),
        Row("FROZEN DESSERT 02DR SB ONT", "Frozen Dessert"),
        Row("FROZEN DESSERT 03DR SB ONT", "Frozen Dessert"),
        Row("FROZEN FRUIT 02DR SB ONT", "Frozen Fruit"),
        Row("FROZEN FRUIT 03DR SB ONT", "Frozen Fruit"),
        Row("FROZEN FRUIT 04DR SB ONT", "Frozen Fruit"),
        Row("FROZEN FRUIT 05DR SB ONT", "Frozen Fruit"),
        Row("FROZEN FRUIT 06DR SB ONT", "Frozen Fruit"),
        Row("FROZEN HANDHELDS 01DR SBY ONT", "Frozen Handhelds"),
        Row("FROZEN HANDHELDS 02DR SBY ONT", "Frozen Handhelds"),
        Row("FROZEN HANDHELDS 03DR SBY ONT", "Frozen Handhelds"),
        Row("FROZEN HANDHELDS 04DR SBY ONT", "Frozen Handhelds"),
        Row("FROZEN HANDHELDS 05DR SBY ONT", "Frozen Handhelds"),
        Row("FROZEN JUICE 01DR SBY ONT", "Frozen Juice"),
        Row("FROZEN JUICE 02DR SBY ONT", "Frozen Juice"),
        Row("FRZ NAT BREADS_GF 01DR 6S SB ONT", "Frozen Natural Breads Gluten Free"),
        Row("FRZ NAT BREADS_GF 02DR 6S SB ONT", "Frozen Natural Breads Gluten Free"),
        Row("FRZ NAT BREADS_GF 03DR 6S SB ONT", "Frozen Natural Breads Gluten Free"),
        Row("FRZ NAT BREADS_GF 04DR 6S SB ONT", "Frozen Natural Breads Gluten Free"),
        Row("FRZ NAT BREADS_GF 05DR 6S SB ONT", "Frozen Natural Breads Gluten Free"),
        Row("FRZ NATURAL BREADS_GF 01DR SB ONT", "Frozen Natural Breads Gluten Free"),
        Row("FRZ NATURAL BREADS_GF 02DR SB ONT", "Frozen Natural Breads Gluten Free"),
        Row("FRZ NATURAL BREADS_GF 03DR SB ONT", "Frozen Natural Breads Gluten Free"),
        Row("FRZ NATURAL BREADS_GF 04DR SB ONT", "Frozen Natural Breads Gluten Free"),
        Row("FROZEN NATURAL COMBO 01DR SB ONT", "Frozen Natural Combo"),
        Row("FROZEN NATURAL COMBO 02DR SB ONT", "Frozen Natural Combo"),
        Row("FROZEN NATURAL COMBO 03DR SB ONT", "Frozen Natural Combo"),
        Row("FROZEN NATURAL COMBO 04DR SB ONT", "Frozen Natural Combo"),
        Row("FROZEN NATURAL COMBO 05DR SB ONT", "Frozen Natural Combo"),
        Row("FROZEN NATURAL COMBO 06DR SB ONT", "Frozen Natural Combo"),
        Row("FROZEN NATURAL COMBO 07DR SB ONT", "Frozen Natural Combo"),
        Row("FROZEN NATURAL COMBO 08DR SB ONT", "Frozen Natural Combo"),
        Row("FRZ NATURAL COMBO 01DR 6S SB ONT", "Frozen Natural Combo"),
        Row("FRZ NATURAL COMBO 02DR 6S SB ONT", "Frozen Natural Combo"),
        Row("FRZ NATURAL COMBO 03DR 6S SB ONT", "Frozen Natural Combo"),
        Row("FRZ NATURAL COMBO 04DR 6S SB ONT", "Frozen Natural Combo"),
        Row("FRZ NATURAL COMBO 05DR 6S SB ONT", "Frozen Natural Combo"),
        Row("FRZ NATURAL COMBO 06DR 6S SB ONT", "Frozen Natural Combo"),
        Row("FRZ NATURAL COMBO 07DR 6S SB ONT", "Frozen Natural Combo"),
        Row("FRZ NATURAL COMBO 08DR 6S SB ONT", "Frozen Natural Combo"),
        Row("FRZ NATURAL COMBO 09DR 6S SB ONT", "Frozen Natural Combo"),
        Row("FRZ NATURAL COMBO 10DR 6S SB ONT", "Frozen Natural Combo"),
        Row("FRZ NAT ENTREES_PIZZ 01DR 6S SB ON", "Frozen Natural Entrees Pizza"),
        Row("FRZ NAT ENTREES_PIZZ 02DR 6S SB ON", "Frozen Natural Entrees Pizza"),
        Row("FRZ NAT ENTREES_PIZZ 03DR 6S SB ON", "Frozen Natural Entrees Pizza"),
        Row("FRZ NAT ENTREES_PIZZ 04DR 6S SB ON", "Frozen Natural Entrees Pizza"),
        Row("FRZ NAT ENTREES_PIZZ 05DR 6S SB ON", "Frozen Natural Entrees Pizza"),
        Row("FRZ NAT ENTREES_PIZZA 01DR SB ONT", "Frozen Natural Entrees Pizza"),
        Row("FRZ NAT ENTREES_PIZZA 02DR SB ONT", "Frozen Natural Entrees Pizza"),
        Row("FRZ NAT ENTREES_PIZZA 03DR SB ONT", "Frozen Natural Entrees Pizza"),
        Row("FRZ NAT ENTREES_PIZZA 04DR SB ONT", "Frozen Natural Entrees Pizza"),
        Row("FROZEN PIZZA 05DR SBY ONT", "Frozen Pizza"),
        Row("FROZEN PIZZA 06DR SBY ONT", "Frozen Pizza"),
        Row("FROZEN PIZZA 07DR SBY ONT", "Frozen Pizza"),
        Row("FROZEN PIZZA 08DR SBY ONT", "Frozen Pizza"),
        Row("FROZEN PIZZA 09DR SBY ONT", "Frozen Pizza"),
        Row("FROZEN PIZZA 10DR SBY ONT", "Frozen Pizza"),
        Row("FROZEN PIZZA 11DR SBY ONT", "Frozen Pizza"),
        Row("FROZEN PIZZA 12DR SBY ONT", "Frozen Pizza"),
        Row("FROZEN PIZZA 13DR SBY ONT", "Frozen Pizza"),
        Row("FROZEN POTATO 03DR SBY ONT", "Frozen Potato"),
        Row("FROZEN POTATO 04DR SBY ONT", "Frozen Potato"),
        Row("FROZEN POTATO 05DR SBY ONT", "Frozen Potato"),
        Row("FROZEN POTATO 06DR SBY ONT", "Frozen Potato"),
        Row("FROZEN POTATO 07DR SBY ONT", "Frozen Potato"),
        Row("FROZEN POTATO 08DR SBY ONT", "Frozen Potato"),
        Row("FROZEN POTATOES 02DR WEST", "Frozen Potato"),
        Row("FROZEN VEGETABLES 03DR SBY ONT", "Frozen Vegetables"),
        Row("FROZEN VEGETABLES 04DR SBY ONT", "Frozen Vegetables"),
        Row("FROZEN VEGETABLES 05DR SBY ONT", "Frozen Vegetables"),
        Row("FROZEN VEGETABLES 06DR SBY ONT", "Frozen Vegetables"),
        Row("FROZEN VEGETABLES 07DR SBY ONT", "Frozen Vegetables"),
        Row("ICE CREAM NOVELTIES 10DR SB ONT", "Ice Cream Novelties"),
        Row("ICE CREAM NOVELTIES 11DR SB ONT", "Ice Cream Novelties"),
        Row("ICE CREAM NOVELTIES 13DR SB ONT", "Ice Cream Novelties"),
        Row("ICE CREAM NOVELTIES 14DR SB ONT", "Ice Cream Novelties"),
        Row("ICE CREAM NOVELTIES 15DR SB ONT", "Ice Cream Novelties"),
        Row("ICE CREAM NOVELTIES 16DR SB ONT", "Ice Cream Novelties"),
        Row("ICE CREAM NOVELTIES 17DR SB ONT", "Ice Cream Novelties"),
        Row("ICE CREAM NOVELTIES 18DR SB ONT", "Ice Cream Novelties"),
        Row("ICE CREAM NOVELTIES 19DR SB ONT", "Ice Cream Novelties"),
        Row("ICE CREAM NOVELTIES 20DR SB ONT", "Ice Cream Novelties"),
        Row("ICE CREAM NOVELTIES 21DR SB ONT", "Ice Cream Novelties"),
        Row("ICE CREAM NOVELTIES 22DR SB ONT", "Ice Cream Novelties"),
        Row("ICE CREAM NOVELTIES 24DR SB ONT", "Ice Cream Novelties"),
        Row("ICE CREAM NOVELTIES 09DR SB ONT", "Ice Cream Novelties"),
    ],
    schema=["SECTION NAME", "SECTION MASTER"],
)
