from pyspark import Row

from tests.utils.spark_util import spark_tests as spark

DF_PRODUCT = spark.createDataFrame(
    [
        Row(
            ITEM_SK="15954718",
            UPC_NO="159547180",
            LVL5_NAME="Rising Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-20",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="DrOetker CasaMamaPizzaPulldPrk",
            ITEM_NO="633928",
            ITEM_ENG_DESC="DrOetker CasaMamaPizzaPulldPrk",
            ITEM_FRN_DESC="DROETKER PIZZA CMAMA PORC EFFILOCHE",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Dr. Oetker",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="14527708",
            UPC_NO="145277080",
            LVL5_NAME="Rising Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-20",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="Delissio RsnC Peprn 12IN",
            ITEM_NO="375039",
            ITEM_ENG_DESC="Delissio RsnC Peprn 12IN",
            ITEM_FRN_DESC="DELISSIO PIZZA LEVE FOUR PEPERON",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Delissio",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="14527707",
            UPC_NO="145277070",
            LVL5_NAME="Traditional Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-22",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="Delisso Pzria Deluxe",
            ITEM_NO="375030",
            ITEM_ENG_DESC="Delisso Pzria Deluxe",
            ITEM_FRN_DESC="DELISSIO PIZZA VINTAGE DELUXE",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Delissio",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="14527712",
            UPC_NO="145277120",
            LVL5_NAME="Rising Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-20",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="Delissio Rsnc 4 Cheese",
            ITEM_NO="375074",
            ITEM_ENG_DESC="Delissio Rsnc 4 Cheese",
            ITEM_FRN_DESC="DELISSIO PIZZA LEVE FOUR 4 FROM",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="DELISSIO",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="17413471",
            UPC_NO="174134710",
            LVL5_NAME="Rising Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-20",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="Delissio Pizza StuffedCrst Pep",
            ITEM_NO="955963",
            ITEM_ENG_DESC="Delissio Pizza StuffedCrst Pep",
            ITEM_FRN_DESC="DELISSIO PIZZA CR FARCIE PEPERON",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Delissio",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="12788484",
            UPC_NO="127884840",
            LVL5_NAME="Thin Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-21",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="Sensatns Pz Pros&Genoa Sal Thn",
            ITEM_NO="282187",
            ITEM_ENG_DESC="Sensatns Pz Pros&Genoa Sal Thn",
            ITEM_FRN_DESC="SENS PIZZA CR MINCE PROSC SALAMI",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Sensations",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="11624934",
            UPC_NO="116249340",
            LVL5_NAME="Rising Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-20",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="DrOetker CasaMama Pizza Deluxe",
            ITEM_NO="164849",
            ITEM_ENG_DESC="DrOetker CasaMama Pizza Deluxe",
            ITEM_FRN_DESC="DROETKER PIZZA CMAMA DELUXE",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Dr.Oetker",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="16382236",
            UPC_NO="163822360",
            LVL5_NAME="Thin Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-21",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="DrOetker Pza CasaDMa ClsscCdn",
            ITEM_NO="678984",
            ITEM_ENG_DESC="DrOetker Pza CasaDMa ClsscCdn",
            ITEM_FRN_DESC="DROETKER PIZZA CMAMA CANADIENNE",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Dr. Oetker",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="16967264",
            UPC_NO="169672640",
            LVL5_NAME="Rising Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-20",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="DrOetker Pizza RiCrust 4Cheese",
            ITEM_NO="819649",
            ITEM_ENG_DESC="DrOetker Pizza RiCrust 4Cheese",
            ITEM_FRN_DESC="DrOetker Pizza RiCrust 4Cheese",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Dr. Oetker Giuseppe",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="14527714",
            UPC_NO="145277140",
            LVL5_NAME="Rising Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-20",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="Delissio RsnC Spcy Chicken",
            ITEM_NO="375083",
            ITEM_ENG_DESC="Delissio RsnC Spcy Chicken",
            ITEM_FRN_DESC="DELISSIO PIZZA LEVE FOUR POUL EP",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Delissio",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="11676176",
            UPC_NO="116761760",
            LVL5_NAME="Thin Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-21",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="DrOetker Ristornt T/Crst PzVeg",
            ITEM_NO="413819",
            ITEM_ENG_DESC="DrOetker Ristornt T/Crst PzVeg",
            ITEM_FRN_DESC="DROETKER PIZZA RIST VEGETARIEN",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Dr.Oetker",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="17182217",
            UPC_NO="171822170",
            LVL5_NAME="Garlic Fingers",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-24",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="SMI Opsite 24632 Dr 5x5in  1ea",
            ITEM_NO="900100",
            ITEM_ENG_DESC="Napoli Pizza Classic Crust Che",
            ITEM_FRN_DESC="Napoli Pizza Classic Crust Cheese",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Napoli",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="12148092",
            UPC_NO="121480920",
            LVL5_NAME="Thin Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-21",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="DrOetker Ristornt Pollo Pizza",
            ITEM_NO="265836",
            ITEM_ENG_DESC="DrOetker Ristornt Pollo Pizza",
            ITEM_FRN_DESC="DROETKER PIZZA RIST POLLO",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Dr.Oetker",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="12787445",
            UPC_NO="127874450",
            LVL5_NAME="Thin Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-21",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="Sensatns Pizza Thin Crst Mzz",
            ITEM_NO="233098",
            ITEM_ENG_DESC="Sensatns Pizza Thin Crst Mzz",
            ITEM_FRN_DESC="SENS PIZZA CR MINCE MOZZARELLA",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Sensations",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="14527709",
            UPC_NO="145277090",
            LVL5_NAME="Rising Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-20",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="Delissio Rsnc Deluxe 12IN",
            ITEM_NO="375044",
            ITEM_ENG_DESC="Delissio Rsnc Deluxe 12IN",
            ITEM_FRN_DESC="DELISSIO PIZZA LEVE FOUR DELUXE",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Delissio",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="15779355",
            UPC_NO="157793550",
            LVL5_NAME="Thin Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-21",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="DrOetker Glusep Thin Can  510g",
            ITEM_NO="576782",
            ITEM_ENG_DESC="DrOetker Giusep Thin Crust Can",
            ITEM_FRN_DESC="GIUSEPPE PIZZA CR MINC CANADIENNE",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Dr.Oetker",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="11673944",
            UPC_NO="116739440",
            LVL5_NAME="Thin Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-21",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="DrOetker Ristornt T/CrstPzaMoz",
            ITEM_NO="405921",
            ITEM_ENG_DESC="DrOetker Ristornt T/CrstPzaMoz",
            ITEM_FRN_DESC="DROETKER PIZZA RIST MOZZARELLA",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Dr.Oetker",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="12787446",
            UPC_NO="127874460",
            LVL5_NAME="Thin Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-21",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="Sensatns Pizza Thin Crst Msh",
            ITEM_NO="233105",
            ITEM_ENG_DESC="Sensatns Pizza Thin Crst Msh",
            ITEM_FRN_DESC="SENS PIZZA CR MINCE CHAMPIGNON",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Sensations",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="18305394",
            UPC_NO="183053940",
            LVL5_NAME="Thin Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ice Cream and Dessert",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-21",
            LVL3_ID="M330",
            LVL2_ID="M33",
            ITEM_NAME="DrOetKer Giusep Thin Crst Spin",
            ITEM_NO="541805",
            ITEM_ENG_DESC="DrOetKer Giusep Thin Crst Spin",
            ITEM_FRN_DESC="GIUSEPPE PIZZA CR MINC EPINARDS",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Dr. Oetker Giuseppe",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
        Row(
            ITEM_SK="13956702",
            UPC_NO="139567020",
            LVL5_NAME="Thin Crust Pizza",
            LVL4_NAME="Frozen Pizza",
            LVL3_NAME="Frozen Ready Meals",
            LVL2_NAME="Frozen Grocery",
            LVL5_ID="303-04-21",
            LVL3_ID="M3304",
            LVL2_ID="M33",
            ITEM_NAME="DrOetker Pizza Pepperoni Pesto",
            ITEM_NO="314792",
            ITEM_ENG_DESC="DrOetker Pizza Pepperoni Pesto",
            ITEM_FRN_DESC="DROETKER PIZZA RIST PEPP PESTO",
            REGION_DESC="Ontario",
            REGION_CD="001",
            BRAND_ENG_NM="Dr.Oetker",
            CATEGORY_ID="33-04-01",
            ITEM_UOM_CD="EA",
        ),
    ]
)
