from tests.utils.spark_util import spark_tests as spark

from pyspark import Row

DF_REGION_BANNER_SECTIONS_FOR_MARGIN_RERUNS = spark.sparkContext.parallelize(
    [
        Row(
            "West",
            "IGA",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenfruitdessert",
            "Frozen Fruit",
            "74",
            "Frozen Fruit",
            "TRUE",
        ),
        Row(
            "West",
            "IGA",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenjuice",
            "Frozen Juice and Drinks",
            "29",
            "Frozen Juice",
            "TRUE",
        ),
        Row(
            "West",
            "IGA",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Icecreamnovelties",
            "Ice Cream",
            "368",
            "Ice Cream Novelties",
            "TRUE",
        ),
        Row(
            "West",
            "IGA",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenpotatoes",
            "Frozen Vegetables",
            "69",
            "Frozen Potato",
            "TRUE",
        ),
        Row(
            "West",
            "IGA",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenvegetables",
            "Frozen Vegetables",
            "62",
            "Frozen Vegetables",
            "TRUE",
        ),
        Row(
            "West",
            "IGA",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Dinnersentrees",
            "Frozen Meals",
            "144",
            "Dinners And Entrees",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frznatentreepizz",
            "Org and Nat - Frozen Meal Makers",
            "93",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenbreakfast",
            "Frozen Breakfast",
            "52",
            "Frozen Breakfast",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Dinnersentrees",
            "Frozen Meals",
            "192",
            "Dinners And Entrees",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Pizzahandhelds",
            "Frozen Pizza",
            "99",
            "Frozen Handhelds",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenpizza",
            "Frozen Pizza",
            "84",
            "Frozen Pizza",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenfruitdessert",
            "Frozen Fruit",
            "63",
            "Frozen Fruit",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenjuice",
            "Frozen Juice and Drinks",
            "29",
            "Frozen Juice",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Icecreamnovelties",
            "Ice Cream",
            "277",
            "Ice Cream Novelties",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenpotatoes",
            "Frozen Vegetables",
            "67",
            "Frozen Potato",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenvegetables",
            "Frozen Vegetables",
            "73",
            "Frozen Vegetables",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frzbreakfastjuice",
            "Frozen Breakfast",
            "32",
            "Frozen Juice",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Pizzahandhelds",
            "Frozen Pizza",
            "100",
            "Frozen Handhelds",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenbreakfast",
            "Frozen Breakfast",
            "52",
            "Frozen Breakfast",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Dinnersentrees",
            "Frozen Meals",
            "149",
            "Dinners And Entrees",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Pizzahandheld",
            "Frozen Pizza",
            "43",
            "Frozen Handhelds",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frzbreakfastjuice",
            "Frozen Breakfast",
            "32",
            "Frozen Juice",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenbreakfast",
            "Frozen Breakfast",
            "52",
            "Frozen Breakfast",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Dinnersentrees",
            "Frozen Meals",
            "161",
            "Dinners And Entrees",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Pizzahandhelds",
            "Frozen Pizza",
            "144",
            "Frozen Handhelds",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenhandhelds",
            "Frozen Pizza",
            "60",
            "Frozen Handhelds",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frznatbreadsgf",
            "Org and Nat - Frozen Meal Makers",
            "109",
            "Frozen Bread GF",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frznaturalcombo",
            "Org and Nat - Frozen Meal Makers",
            "201",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frznaturalbreadsgf",
            "Org and Nat - Frozen Meal Makers",
            "109",
            "Frozen Bread GF",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenfruitdessert",
            "Frozen Fruit",
            "49",
            "Frozen Fruit",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenpotatoes",
            "Frozen Vegetables",
            "78",
            "Frozen Potato",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frznatentreespizza",
            "Org and Nat - Frozen Meal Makers",
            "93",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenvegetables",
            "Frozen Vegetables",
            "97",
            "Frozen Vegetables",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozendessert",
            "Frozen Dessert, Dough and Whipped Toppin",
            "31",
            "Frozen Dessert",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Icecreamnovelties",
            "Ice Cream",
            "336",
            "Ice Cream Novelties",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenfruit",
            "Frozen Fruit",
            "55",
            "Frozen Fruit",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenfruitdessert",
            "Frozen Fruit",
            "74",
            "Frozen Fruit",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenpotatoes",
            "Frozen Vegetables",
            "72",
            "Frozen Potato",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenvegetables",
            "Frozen Vegetables",
            "70",
            "Frozen Vegetables",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozennaturalcombo",
            "Org and Nat - Frozen Meal Makers",
            "92",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenfruit",
            "Frozen Fruit",
            "55",
            "Frozen Fruit",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenjuice",
            "Frozen Juice and Drinks",
            "29",
            "Frozen Juice",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozendessert",
            "Frozen Dessert, Dough and Whipped Toppin",
            "30",
            "Frozen Dessert",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozennaturalcombo",
            "Org and Nat - Frozen Meal Makers",
            "201",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Icecreamnovelties",
            "Ice Cream",
            "366",
            "Ice Cream Novelties",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frznhandhld",
            "Frozen Pizza",
            "38",
            "Frozen Handhelds",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenpizza",
            "Frozen Pizza",
            "74",
            "Frozen Pizza",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenfruit",
            "Frozen Fruit",
            "21",
            "Frozen Fruit",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozensouthasian",
            "Frozen Snacks and Appetizers",
            "247",
            "Frozen International",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Perogies",
            "Frozen Dinner and Lunch Components",
            "14",
            "Frozen International",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozengreek",
            "Frozen Snacks and Appetizers",
            "28",
            "Frozen International",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenvegetable",
            "Frozen Vegetables",
            "55",
            "Frozen Vegetables",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FOODLAND",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenjuice",
            "Frozen Juice and Drinks",
            "29",
            "Frozen Juice",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Dinnersentrees",
            "Frozen Meals",
            "191",
            "Dinners And Entrees",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenhandhelds",
            "Frozen Pizza",
            "62",
            "Frozen Handhelds",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenbreakfast",
            "Frozen Breakfast",
            "52",
            "Frozen Breakfast",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frznatbreadsgf",
            "Org and Nat - Frozen Meal Makers",
            "99",
            "Frozen Bread GF",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frznaturalbreadsgf",
            "Org and Nat - Frozen Meal Makers",
            "73",
            "Frozen Bread GF",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frznatentreepizz",
            "Org and Nat - Frozen Meal Makers",
            "96",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenvegetables",
            "Frozen Vegetables",
            "84",
            "Frozen Vegetables",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenpotatoes",
            "Frozen Vegetables",
            "83",
            "Frozen Potato",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Multiculturalfrozen",
            "Frozen Snacks and Appetizers",
            "70",
            "Frozen International",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Icecreamnovelties",
            "Ice Cream",
            "336",
            "Ice Cream Novelties",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenjuice",
            "Frozen Juice and Drinks",
            "29",
            "Frozen Juice",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frznatbreadsgf",
            "Org and Nat - Frozen Meal Makers",
            "109",
            "Frozen Bread GF",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozendessert",
            "Frozen Dessert, Dough and Whipped Toppin",
            "30",
            "Frozen Dessert",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frznatentreespizz",
            "Org and Nat - Frozen Meal Makers",
            "94",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "West",
            "IGA",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenbreakfast",
            "Frozen Breakfast",
            "52",
            "Frozen Breakfast",
            "TRUE",
        ),
        Row(
            "West",
            "IGA",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Pizzahandhelds",
            "Frozen Pizza",
            "78",
            "Frozen Handhelds",
            "TRUE",
        ),
        Row(
            "West",
            "IGA",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenbreakfastjuice",
            "Frozen Breakfast",
            "54",
            "Frozen Juice",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frznaturalcombo",
            "Org and Nat - Frozen Meal Makers",
            "202",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenmiddleeastern",
            "Frozen Vegetables",
            "47",
            "Frozen International",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenfries",
            "Frozen Vegetables",
            "42",
            "Frozen Potato",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenferma",
            "Frozen Vegetables",
            "6",
            "Frozen Vegetables",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenbreakfast",
            "Frozen Breakfast",
            "42",
            "Frozen Breakfast",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozendinners",
            "Frozen Meals",
            "135",
            "Dinners And Entrees",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Organicfrozen",
            "Org and Nat - Frozen Ready Meals",
            "20",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Multiculturalicdessert",
            "Ice Cream",
            "64",
            "Frozen Dessert",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Multiculturalicecream",
            "Ice Cream",
            "31",
            "Ice Cream Novelties",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenmiddleeastern",
            "Frozen Vegetables",
            "27",
            "Frozen International",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenfilipino",
            "Frozen Snacks and Appetizers",
            "115",
            "Frozen International",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozeneastasian",
            "Frozen Snacks and Appetizers",
            "83",
            "Frozen International",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozengreek",
            "Frozen Snacks and Appetizers",
            "28",
            "Frozen International",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenpotatoes",
            "Frozen Vegetables",
            "83",
            "Frozen Potato",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Dinnersentrees",
            "Frozen Meals",
            "184",
            "Dinners And Entrees",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenbreakfast",
            "Frozen Breakfast",
            "52",
            "Frozen Breakfast",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenhandhelds",
            "Frozen Pizza",
            "61",
            "Frozen Handhelds",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenpizza",
            "Frozen Pizza",
            "81",
            "Frozen Pizza",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozendinners",
            "Frozen Meals",
            "135",
            "Dinners And Entrees",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenpizza",
            "Frozen Pizza",
            "72",
            "Frozen Pizza",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenbreakfast",
            "Frozen Breakfast",
            "43",
            "Frozen Breakfast",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Fznhandheld",
            "Frozen Pizza",
            "38",
            "Frozen Handhelds",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frznhandhld",
            "Frozen Pizza",
            "39",
            "Frozen Handhelds",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frznatentreespizza",
            "Org and Nat - Frozen Meal Makers",
            "96",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozennaturalcombo",
            "Org and Nat - Frozen Meal Makers",
            "194",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Icecreamnovelties",
            "Ice Cream",
            "368",
            "Ice Cream Novelties",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozendessert",
            "Frozen Dessert, Dough and Whipped Toppin",
            "30",
            "Frozen Dessert",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frznaturalcombo",
            "Org and Nat - Frozen Meal Makers",
            "194",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenicecream",
            "Ice Cream",
            "232",
            "Ice Cream Novelties",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozendessertwfruit",
            "Frozen Fruit",
            "40",
            "Frozen Fruit",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frzndessertwfruit",
            "Frozen Fruit",
            "40",
            "Frozen Fruit",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenjuice",
            "Frozen Juice and Drinks",
            "29",
            "Frozen Juice",
            "TRUE",
        ),
        Row(
            "West",
            "THRIFTY FOODS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenfruit",
            "Frozen Fruit",
            "61",
            "Frozen Fruit",
            "TRUE",
        ),
        Row(
            "West",
            "THRIFTY FOODS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenjuice",
            "Frozen Juice and Drinks",
            "22",
            "Frozen Juice",
            "TRUE",
        ),
        Row(
            "West",
            "THRIFTY FOODS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozendessert",
            "Frozen Dessert, Dough and Whipped Toppin",
            "36",
            "Frozen Dessert",
            "TRUE",
        ),
        Row(
            "West",
            "THRIFTY FOODS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Icecreamnovelties",
            "Ice Cream",
            "280",
            "Ice Cream Novelties",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Icecreamnovelties",
            "Ice Cream",
            "368",
            "Ice Cream Novelties",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozendessert",
            "Frozen Dessert, Dough and Whipped Toppin",
            "30",
            "Frozen Dessert",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenfruit",
            "Frozen Fruit",
            "55",
            "Frozen Fruit",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenjuice",
            "Frozen Juice and Drinks",
            "29",
            "Frozen Juice",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frznaturalcombo",
            "Org and Nat - Frozen Meal Makers",
            "194",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frznatbreadsgf",
            "Org and Nat - Frozen Meal Makers",
            "111",
            "Frozen Bread GF",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenfruit",
            "Frozen Fruit",
            "55",
            "Frozen Fruit",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenjuice",
            "Frozen Juice and Drinks",
            "29",
            "Frozen Juice",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenvegetables",
            "Frozen Vegetables",
            "84",
            "Frozen Vegetables",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frznatentreepizz",
            "Org and Nat - Frozen Meal Makers",
            "88",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Multiculturalfrozen",
            "Frozen Snacks and Appetizers",
            "89",
            "Frozen International",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenpizza",
            "Frozen Pizza",
            "81",
            "Frozen Pizza",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Dinnersentrees",
            "Frozen Meals",
            "184",
            "Dinners And Entrees",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenhandhelds",
            "Frozen Pizza",
            "61",
            "Frozen Handhelds",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenbreakfast",
            "Frozen Breakfast",
            "52",
            "Frozen Breakfast",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenfruit",
            "Frozen Fruit",
            "55",
            "Frozen Fruit",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozennaturalcombo",
            "Org and Nat - Frozen Meal Makers",
            "123",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenvegetables",
            "Frozen Vegetables",
            "84",
            "Frozen Vegetables",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frznatentreespizza",
            "Org and Nat - Frozen Meal Makers",
            "76",
            "Frozen Natural",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenpotato",
            "Frozen Vegetables",
            "79",
            "Frozen Potato",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenpizza",
            "Frozen Pizza",
            "84",
            "Frozen Pizza",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Perogies",
            "Frozen Dinner and Lunch Components",
            "14",
            "Frozen International",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenfries",
            "Frozen Vegetables",
            "40",
            "Frozen Potato",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozensouthasian",
            "Frozen Vegetables",
            "295",
            "Frozen International",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenvegetable",
            "Frozen Vegetables",
            "55",
            "Frozen Vegetables",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozensasian",
            "Frozen Snacks and Appetizers",
            "88",
            "Frozen International",
            "TRUE",
        ),
        Row(
            "West",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenferma",
            "Frozen Vegetables",
            "6",
            "Frozen Vegetables",
            "TRUE",
        ),
        Row(
            "West",
            "THRIFTY FOODS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenpotatoes",
            "Frozen Vegetables",
            "72",
            "Frozen Potato",
            "TRUE",
        ),
        Row(
            "West",
            "THRIFTY FOODS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Meal Makers",
            "Frozenvegetables",
            "Frozen Vegetables",
            "74",
            "Frozen Vegetables",
            "TRUE",
        ),
        Row(
            "West",
            "THRIFTY FOODS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenpizzahandhelds",
            "Frozen Pizza",
            "88",
            "Frozen Handhelds",
            "TRUE",
        ),
        Row(
            "West",
            "THRIFTY FOODS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Frozenbreakfast",
            "Frozen Breakfast",
            "50",
            "Frozen Breakfast",
            "TRUE",
        ),
        Row(
            "West",
            "THRIFTY FOODS",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ready Meals",
            "Dinnersentrees",
            "Frozen Meals",
            "173",
            "Dinners And Entrees",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozendessertwfruit",
            "Frozen Dessert, Dough and Whipped Toppin",
            "40",
            "Frozen Dessert",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Multiculturalicecream",
            "Ice Cream",
            "34",
            "Ice Cream Novelties",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenicecream",
            "Ice Cream",
            "251",
            "Ice Cream Novelties",
            "TRUE",
        ),
        Row(
            "Ontario",
            "FRESH CO",
            "Frozen Grocery",
            "Frozen",
            "Frozen Ice Cream and Dessert",
            "Frozenjuice",
            "Frozen Juice and Drinks",
            "30",
            "Frozen Juice",
            "TRUE",
        ),
        Row(
            "Ontario",
            "SOBEYS",
            "Meat",
            "Frozen",
            "Frozen Meat",
            "Frozenboxedmeat",
            "Frz Boxed Bxd Brdd P",
            "234",
            "Frozen Meat",
            "TRUE",
        ),
        Row(
            "West",
            "SAFEWAY",
            "Meat",
            "Frozen",
            "Frozen Meat",
            "Frozenboxedmeatwest",
            "Frz Boxed Bxd Brdd P",
            "216",
            "Frozen Meat",
            "TRUE",
        ),
        Row(
            "West",
            "SOBEYS",
            "Meat",
            "Frozen",
            "Frozen Meat",
            "Frozenboxedmeatwest",
            "Frz Boxed Bxd Brdd P",
            "193",
            "Frozen Meat",
            "TRUE",
        ),
        Row(
            "Atlantic",
            "SOBEYS",
            "Meat",
            "Frozen",
            "Frozen Meat",
            "Frozenboxedmeat",
            "Frz Boxed Bxd Brdd P",
            "202",
            "Frozen Meat",
            "TRUE",
        ),
    ]
).toDF(
    [
        "Region",
        "Banner",
        "PM_LVL2_Tag",
        "Department",
        "PM_LVL3_Tag",
        "UPDATED_SECTION_MASTER",
        "PM_LVL4_Mode",
        "Item_Count",
        "SECTION_MASTER",
        "(Role = Credible or Trigger, If TRUE -> Rerun if cluster is non-price sensitive)",
    ]
)
