from pyspark import Row

from tests.utils.spark_util import spark_tests as spark


DF_SECTION_MASTER_OVERRIDE = spark.createDataFrame(
    [
        Row(
            Region="West",
            Banner="IGA",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenfruitdessert",
            PM_LVL4_Mode="Frozen Fruit",
            Item_Count="74",
            UPDATED_SECTION_MASTER="Frozen Fruit",
        ),
        Row(
            Region="West",
            Banner="IGA",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenjuice",
            PM_LVL4_Mode="Frozen Juice and Drinks",
            Item_Count="29",
            UPDATED_SECTION_MASTER="Frozen Juice",
        ),
        Row(
            Region="West",
            Banner="IGA",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Icecreamnovelties",
            PM_LVL4_Mode="Ice Cream",
            Item_Count="368",
            UPDATED_SECTION_MASTER="Ice Cream Novelties",
        ),
        Row(
            Region="West",
            Banner="IGA",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenpotatoes",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="69",
            UPDATED_SECTION_MASTER="Frozen Potato",
        ),
        Row(
            Region="West",
            Banner="IGA",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenvegetables",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="62",
            UPDATED_SECTION_MASTER="Frozen Vegetables",
        ),
        Row(
            Region="West",
            Banner="IGA",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Dinnersentrees",
            PM_LVL4_Mode="Frozen Meals",
            Item_Count="144",
            UPDATED_SECTION_MASTER="Dinners And Entrees",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frznatentreepizz",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="93",
            UPDATED_SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenbreakfast",
            PM_LVL4_Mode="Frozen Breakfast",
            Item_Count="52",
            UPDATED_SECTION_MASTER="Frozen Breakfast",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Dinnersentrees",
            PM_LVL4_Mode="Frozen Meals",
            Item_Count="192",
            UPDATED_SECTION_MASTER="Dinners And Entrees",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Pizzahandhelds",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="99",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenpizza",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="84",
            UPDATED_SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            Region="Atlantic",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenfruitdessert",
            PM_LVL4_Mode="Frozen Fruit",
            Item_Count="63",
            UPDATED_SECTION_MASTER="Frozen Fruit",
        ),
        Row(
            Region="Atlantic",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenjuice",
            PM_LVL4_Mode="Frozen Juice and Drinks",
            Item_Count="29",
            UPDATED_SECTION_MASTER="Frozen Juice",
        ),
        Row(
            Region="Atlantic",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Icecreamnovelties",
            PM_LVL4_Mode="Ice Cream",
            Item_Count="277",
            UPDATED_SECTION_MASTER="Ice Cream Novelties",
        ),
        Row(
            Region="Atlantic",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenpotatoes",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="67",
            UPDATED_SECTION_MASTER="Frozen Potato",
        ),
        Row(
            Region="Atlantic",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenvegetables",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="73",
            UPDATED_SECTION_MASTER="Frozen Vegetables",
        ),
        Row(
            Region="Atlantic",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frzbreakfastjuice",
            PM_LVL4_Mode="Frozen Breakfast",
            Item_Count="32",
            UPDATED_SECTION_MASTER="Frozen Juice",
        ),
        Row(
            Region="Atlantic",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Pizzahandhelds",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="100",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="Atlantic",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenbreakfast",
            PM_LVL4_Mode="Frozen Breakfast",
            Item_Count="52",
            UPDATED_SECTION_MASTER="Frozen Breakfast",
        ),
        Row(
            Region="Atlantic",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Dinnersentrees",
            PM_LVL4_Mode="Frozen Meals",
            Item_Count="149",
            UPDATED_SECTION_MASTER="Dinners And Entrees",
        ),
        Row(
            Region="Ontario",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Pizzahandheld",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="43",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="Ontario",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frzbreakfastjuice",
            PM_LVL4_Mode="Frozen Breakfast",
            Item_Count="32",
            UPDATED_SECTION_MASTER="Frozen Juice",
        ),
        Row(
            Region="Ontario",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenbreakfast",
            PM_LVL4_Mode="Frozen Breakfast",
            Item_Count="52",
            UPDATED_SECTION_MASTER="Frozen Breakfast",
        ),
        Row(
            Region="Ontario",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Dinnersentrees",
            PM_LVL4_Mode="Frozen Meals",
            Item_Count="161",
            UPDATED_SECTION_MASTER="Dinners And Entrees",
        ),
        Row(
            Region="Ontario",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Pizzahandhelds",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="144",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenhandhelds",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="60",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frznatbreadsgf",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="109",
            UPDATED_SECTION_MASTER="Frozen Bread GF",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frznaturalcombo",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="201",
            UPDATED_SECTION_MASTER="Frozen Natural",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frznaturalbreadsgf",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="109",
            UPDATED_SECTION_MASTER="Frozen Bread GF",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenfruitdessert",
            PM_LVL4_Mode="Frozen Fruit",
            Item_Count="49",
            UPDATED_SECTION_MASTER="Frozen Fruit",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenpotatoes",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="78",
            UPDATED_SECTION_MASTER="Frozen Potato",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frznatentreespizza",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="93",
            UPDATED_SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenvegetables",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="97",
            UPDATED_SECTION_MASTER="Frozen Vegetables",
        ),
        Row(
            Region="Ontario",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozendessert",
            PM_LVL4_Mode="Frozen Dessert, Dough and Whipped Toppin",
            Item_Count="31",
            UPDATED_SECTION_MASTER="Frozen Dessert",
        ),
        Row(
            Region="Ontario",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Icecreamnovelties",
            PM_LVL4_Mode="Ice Cream",
            Item_Count="336",
            UPDATED_SECTION_MASTER="Ice Cream Novelties",
        ),
        Row(
            Region="Ontario",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenfruit",
            PM_LVL4_Mode="Frozen Fruit",
            Item_Count="55",
            UPDATED_SECTION_MASTER="Frozen Fruit",
        ),
        Row(
            Region="Ontario",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenfruitdessert",
            PM_LVL4_Mode="Frozen Fruit",
            Item_Count="74",
            UPDATED_SECTION_MASTER="Frozen Fruit",
        ),
        Row(
            Region="Ontario",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenpotatoes",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="72",
            UPDATED_SECTION_MASTER="Frozen Potato",
        ),
        Row(
            Region="Ontario",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenvegetables",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="70",
            UPDATED_SECTION_MASTER="Frozen Vegetables",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozennaturalcombo",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="92",
            UPDATED_SECTION_MASTER="Frozen Natural",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenfruit",
            PM_LVL4_Mode="Frozen Fruit",
            Item_Count="55",
            UPDATED_SECTION_MASTER="Frozen Fruit",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenjuice",
            PM_LVL4_Mode="Frozen Juice and Drinks",
            Item_Count="29",
            UPDATED_SECTION_MASTER="Frozen Juice",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozendessert",
            PM_LVL4_Mode="Frozen Dessert, Dough and Whipped Toppin",
            Item_Count="30",
            UPDATED_SECTION_MASTER="Frozen Dessert",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozennaturalcombo",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="201",
            UPDATED_SECTION_MASTER="Frozen Natural",
        ),
        Row(
            Region="Atlantic",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Icecreamnovelties",
            PM_LVL4_Mode="Ice Cream",
            Item_Count="366",
            UPDATED_SECTION_MASTER="Ice Cream Novelties",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frznhandhld",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="38",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenpizza",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="74",
            UPDATED_SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenfruit",
            PM_LVL4_Mode="Frozen Fruit",
            Item_Count="21",
            UPDATED_SECTION_MASTER="Frozen Fruit",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozensouthasian",
            PM_LVL4_Mode="Frozen Snacks and Appetizers",
            Item_Count="247",
            UPDATED_SECTION_MASTER="Frozen International",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Perogies",
            PM_LVL4_Mode="Frozen Dinner and Lunch Components",
            Item_Count="14",
            UPDATED_SECTION_MASTER="Frozen International",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozengreek",
            PM_LVL4_Mode="Frozen Snacks and Appetizers",
            Item_Count="28",
            UPDATED_SECTION_MASTER="Frozen International",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenvegetable",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="55",
            UPDATED_SECTION_MASTER="Frozen Vegetables",
        ),
        Row(
            Region="Ontario",
            Banner="FOODLAND",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenjuice",
            PM_LVL4_Mode="Frozen Juice and Drinks",
            Item_Count="29",
            UPDATED_SECTION_MASTER="Frozen Juice",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Dinnersentrees",
            PM_LVL4_Mode="Frozen Meals",
            Item_Count="191",
            UPDATED_SECTION_MASTER="Dinners And Entrees",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenhandhelds",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="62",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenbreakfast",
            PM_LVL4_Mode="Frozen Breakfast",
            Item_Count="52",
            UPDATED_SECTION_MASTER="Frozen Breakfast",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frznatbreadsgf",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="99",
            UPDATED_SECTION_MASTER="Frozen Bread GF",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frznaturalbreadsgf",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="73",
            UPDATED_SECTION_MASTER="Frozen Bread GF",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frznatentreepizz",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="96",
            UPDATED_SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenvegetables",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="84",
            UPDATED_SECTION_MASTER="Frozen Vegetables",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenpotatoes",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="83",
            UPDATED_SECTION_MASTER="Frozen Potato",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Multiculturalfrozen",
            PM_LVL4_Mode="Frozen Snacks and Appetizers",
            Item_Count="70",
            UPDATED_SECTION_MASTER="Frozen International",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Icecreamnovelties",
            PM_LVL4_Mode="Ice Cream",
            Item_Count="336",
            UPDATED_SECTION_MASTER="Ice Cream Novelties",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenjuice",
            PM_LVL4_Mode="Frozen Juice and Drinks",
            Item_Count="29",
            UPDATED_SECTION_MASTER="Frozen Juice",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frznatbreadsgf",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="109",
            UPDATED_SECTION_MASTER="Frozen Bread GF",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozendessert",
            PM_LVL4_Mode="Frozen Dessert, Dough and Whipped Toppin",
            Item_Count="30",
            UPDATED_SECTION_MASTER="Frozen Dessert",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frznatentreespizz",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="94",
            UPDATED_SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            Region="West",
            Banner="IGA",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenbreakfast",
            PM_LVL4_Mode="Frozen Breakfast",
            Item_Count="52",
            UPDATED_SECTION_MASTER="Frozen Breakfast",
        ),
        Row(
            Region="West",
            Banner="IGA",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Pizzahandhelds",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="78",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Pizzahandhelds",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="78",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="West",
            Banner="IGA",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenbreakfastjuice",
            PM_LVL4_Mode="Frozen Breakfast",
            Item_Count="54",
            UPDATED_SECTION_MASTER="Frozen Juice",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frznaturalcombo",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="202",
            UPDATED_SECTION_MASTER="Frozen Natural",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenmiddleeastern",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="47",
            UPDATED_SECTION_MASTER="Frozen International",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenfries",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="42",
            UPDATED_SECTION_MASTER="Frozen Potato",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenferma",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="6",
            UPDATED_SECTION_MASTER="Frozen Vegetables",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenbreakfast",
            PM_LVL4_Mode="Frozen Breakfast",
            Item_Count="42",
            UPDATED_SECTION_MASTER="Frozen Breakfast",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozendinners",
            PM_LVL4_Mode="Frozen Meals",
            Item_Count="135",
            UPDATED_SECTION_MASTER="Dinners And Entrees",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Organicfrozen",
            PM_LVL4_Mode="Org and Nat - Frozen Ready Meals",
            Item_Count="20",
            UPDATED_SECTION_MASTER="Frozen Natural",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Multiculturalicdessert",
            PM_LVL4_Mode="Ice Cream",
            Item_Count="64",
            UPDATED_SECTION_MASTER="Frozen Dessert",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Multiculturalicecream",
            PM_LVL4_Mode="Ice Cream",
            Item_Count="31",
            UPDATED_SECTION_MASTER="Ice Cream Novelties",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenmiddleeastern",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="27",
            UPDATED_SECTION_MASTER="Frozen International",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenfilipino",
            PM_LVL4_Mode="Frozen Snacks and Appetizers",
            Item_Count="115",
            UPDATED_SECTION_MASTER="Frozen International",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozeneastasian",
            PM_LVL4_Mode="Frozen Snacks and Appetizers",
            Item_Count="83",
            UPDATED_SECTION_MASTER="Frozen International",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozengreek",
            PM_LVL4_Mode="Frozen Snacks and Appetizers",
            Item_Count="28",
            UPDATED_SECTION_MASTER="Frozen International",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenpotatoes",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="83",
            UPDATED_SECTION_MASTER="Frozen Potato",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Dinnersentrees",
            PM_LVL4_Mode="Frozen Meals",
            Item_Count="184",
            UPDATED_SECTION_MASTER="Dinners And Entrees",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenbreakfast",
            PM_LVL4_Mode="Frozen Breakfast",
            Item_Count="52",
            UPDATED_SECTION_MASTER="Frozen Breakfast",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenhandhelds",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="61",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenpizza",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="81",
            UPDATED_SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozendinners",
            PM_LVL4_Mode="Frozen Meals",
            Item_Count="135",
            UPDATED_SECTION_MASTER="Dinners And Entrees",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenpizza",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="72",
            UPDATED_SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenbreakfast",
            PM_LVL4_Mode="Frozen Breakfast",
            Item_Count="43",
            UPDATED_SECTION_MASTER="Frozen Breakfast",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Fznhandheld",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="38",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frznhandhld",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="39",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frznatentreespizza",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="96",
            UPDATED_SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozennaturalcombo",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="194",
            UPDATED_SECTION_MASTER="Frozen Natural",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Icecreamnovelties",
            PM_LVL4_Mode="Ice Cream",
            Item_Count="368",
            UPDATED_SECTION_MASTER="Ice Cream Novelties",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozendessert",
            PM_LVL4_Mode="Frozen Dessert, Dough and Whipped Toppin",
            Item_Count="30",
            UPDATED_SECTION_MASTER="Frozen Dessert",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frznaturalcombo",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="194",
            UPDATED_SECTION_MASTER="Frozen Natural",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenicecream",
            PM_LVL4_Mode="Ice Cream",
            Item_Count="232",
            UPDATED_SECTION_MASTER="Ice Cream Novelties",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozendessertwfruit",
            PM_LVL4_Mode="Frozen Fruit",
            Item_Count="40",
            UPDATED_SECTION_MASTER="Frozen Fruit",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frzndessertwfruit",
            PM_LVL4_Mode="Frozen Fruit",
            Item_Count="40",
            UPDATED_SECTION_MASTER="Frozen Fruit",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenjuice",
            PM_LVL4_Mode="Frozen Juice and Drinks",
            Item_Count="29",
            UPDATED_SECTION_MASTER="Frozen Juice",
        ),
        Row(
            Region="West",
            Banner="THRIFTY FOODS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenfruit",
            PM_LVL4_Mode="Frozen Fruit",
            Item_Count="61",
            UPDATED_SECTION_MASTER="Frozen Fruit",
        ),
        Row(
            Region="West",
            Banner="THRIFTY FOODS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenjuice",
            PM_LVL4_Mode="Frozen Juice and Drinks",
            Item_Count="22",
            UPDATED_SECTION_MASTER="Frozen Juice",
        ),
        Row(
            Region="West",
            Banner="THRIFTY FOODS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozendessert",
            PM_LVL4_Mode="Frozen Dessert, Dough and Whipped Toppin",
            Item_Count="36",
            UPDATED_SECTION_MASTER="Frozen Dessert",
        ),
        Row(
            Region="West",
            Banner="THRIFTY FOODS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Icecreamnovelties",
            PM_LVL4_Mode="Ice Cream",
            Item_Count="280",
            UPDATED_SECTION_MASTER="Ice Cream Novelties",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Icecreamnovelties",
            PM_LVL4_Mode="Ice Cream",
            Item_Count="368",
            UPDATED_SECTION_MASTER="Ice Cream Novelties",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozendessert",
            PM_LVL4_Mode="Frozen Dessert, Dough and Whipped Toppin",
            Item_Count="30",
            UPDATED_SECTION_MASTER="Frozen Dessert",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenfruit",
            PM_LVL4_Mode="Frozen Fruit",
            Item_Count="55",
            UPDATED_SECTION_MASTER="Frozen Fruit",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenjuice",
            PM_LVL4_Mode="Frozen Juice and Drinks",
            Item_Count="29",
            UPDATED_SECTION_MASTER="Frozen Juice",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frznaturalcombo",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="194",
            UPDATED_SECTION_MASTER="Frozen Natural",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frznatbreadsgf",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="111",
            UPDATED_SECTION_MASTER="Frozen Bread GF",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenfruit",
            PM_LVL4_Mode="Frozen Fruit",
            Item_Count="55",
            UPDATED_SECTION_MASTER="Frozen Fruit",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenjuice",
            PM_LVL4_Mode="Frozen Juice and Drinks",
            Item_Count="29",
            UPDATED_SECTION_MASTER="Frozen Juice",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenvegetables",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="84",
            UPDATED_SECTION_MASTER="Frozen Vegetables",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frznatentreepizz",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="88",
            UPDATED_SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            Region="West",
            Banner="SAFEWAY",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Multiculturalfrozen",
            PM_LVL4_Mode="Frozen Snacks and Appetizers",
            Item_Count="89",
            UPDATED_SECTION_MASTER="Frozen International",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenpizza",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="81",
            UPDATED_SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Dinnersentrees",
            PM_LVL4_Mode="Frozen Meals",
            Item_Count="184",
            UPDATED_SECTION_MASTER="Dinners And Entrees",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenhandhelds",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="61",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="West",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenbreakfast",
            PM_LVL4_Mode="Frozen Breakfast",
            Item_Count="52",
            UPDATED_SECTION_MASTER="Frozen Breakfast",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenfruit",
            PM_LVL4_Mode="Frozen Fruit",
            Item_Count="55",
            UPDATED_SECTION_MASTER="Frozen Fruit",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozennaturalcombo",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="123",
            UPDATED_SECTION_MASTER="Frozen Natural",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenvegetables",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="84",
            UPDATED_SECTION_MASTER="Frozen Vegetables",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frznatentreespizza",
            PM_LVL4_Mode="Org and Nat - Frozen Meal Makers",
            Item_Count="76",
            UPDATED_SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenpotato",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="79",
            UPDATED_SECTION_MASTER="Frozen Potato",
        ),
        Row(
            Region="Ontario",
            Banner="SOBEYS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenpizza",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="84",
            UPDATED_SECTION_MASTER="Frozen Pizza",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Perogies",
            PM_LVL4_Mode="Frozen Dinner and Lunch Components",
            Item_Count="14",
            UPDATED_SECTION_MASTER="Frozen International",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenfries",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="40",
            UPDATED_SECTION_MASTER="Frozen Potato",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozensouthasian",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="295",
            UPDATED_SECTION_MASTER="Frozen International",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenvegetable",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="55",
            UPDATED_SECTION_MASTER="Frozen Vegetables",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozensasian",
            PM_LVL4_Mode="Frozen Snacks and Appetizers",
            Item_Count="88",
            UPDATED_SECTION_MASTER="Frozen International",
        ),
        Row(
            Region="West",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenferma",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="6",
            UPDATED_SECTION_MASTER="Frozen Vegetables",
        ),
        Row(
            Region="West",
            Banner="THRIFTY FOODS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenpotatoes",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="72",
            UPDATED_SECTION_MASTER="Frozen Potato",
        ),
        Row(
            Region="West",
            Banner="THRIFTY FOODS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Meal Makers",
            SECTION_MASTER="Frozenvegetables",
            PM_LVL4_Mode="Frozen Vegetables",
            Item_Count="74",
            UPDATED_SECTION_MASTER="Frozen Vegetables",
        ),
        Row(
            Region="West",
            Banner="THRIFTY FOODS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenpizzahandhelds",
            PM_LVL4_Mode="Frozen Pizza",
            Item_Count="88",
            UPDATED_SECTION_MASTER="Frozen Handhelds",
        ),
        Row(
            Region="West",
            Banner="THRIFTY FOODS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Frozenbreakfast",
            PM_LVL4_Mode="Frozen Breakfast",
            Item_Count="50",
            UPDATED_SECTION_MASTER="Frozen Breakfast",
        ),
        Row(
            Region="West",
            Banner="THRIFTY FOODS",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ready Meals",
            SECTION_MASTER="Dinnersentrees",
            PM_LVL4_Mode="Frozen Meals",
            Item_Count="173",
            UPDATED_SECTION_MASTER="Dinners And Entrees",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozendessertwfruit",
            PM_LVL4_Mode="Frozen Dessert, Dough and Whipped Toppin",
            Item_Count="40",
            UPDATED_SECTION_MASTER="Frozen Dessert",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Multiculturalicecream",
            PM_LVL4_Mode="Ice Cream",
            Item_Count="34",
            UPDATED_SECTION_MASTER="Ice Cream Novelties",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenicecream",
            PM_LVL4_Mode="Ice Cream",
            Item_Count="251",
            UPDATED_SECTION_MASTER="Ice Cream Novelties",
        ),
        Row(
            Region="Ontario",
            Banner="FRESH CO",
            PM_LVL2_Tag="Frozen Grocery",
            PM_LVL3_Tag="Frozen Ice Cream and Dessert",
            SECTION_MASTER="Frozenjuice",
            PM_LVL4_Mode="Frozen Juice and Drinks",
            Item_Count="30",
            UPDATED_SECTION_MASTER="Frozen Juice",
        ),
    ]
)
